/* Madrid guide data.
 * Coordinates: listed where given; otherwise Wikipedia or OSM Nominatim.
 * Do not add places, quotes, or prices that are not in this file.
 * Hours: official / Turismo Madrid / venue sites. Unknown or seasonal → Hours: check site.
 * Photos: Wikimedia Commons only (hotlink + credit). Skip if no Commons file.
 * kind: food | shopping | sites | landmarks (main filters). Keep category for map colors.
 * why: one short line, max ~12 words, from takeaway/use.
 * rating: only when sourced { score, count?, source, asOf }. Never invent.
 */
window.GUIDE = {
  hotel: {
    lat: 40.41857,
    lng: -3.70267,
  },
  /* Default view: Sol/Gran Vía at the south, Chamberí/Malasaña to the north */
  map: {
    center: [40.4282, -3.7024],
    zoom: 14,
  },
  categories: [
    { id: "stay", label: "Stay" },
    { id: "food", label: "Eat" },
    { id: "markets", label: "Markets" },
    { id: "entertainment", label: "See" },
  ],
  kinds: [
    {
      id: "food",
      label: "Food",
      icon: "🍽️",
      photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Casa%20Bot%C3%ADn-Madrid-2009.jpg?width=400",
      photoAlt: "Sobrino de Botín",
    },
    {
      id: "shopping",
      label: "Shopping",
      icon: "🛍️",
      photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Rastro%20-%20Plaza%20de%20Cascorro%20-%20Madrid%2002.jpg?width=400",
      photoAlt: "El Rastro at Plaza de Cascorro",
    },
    {
      id: "sites",
      label: "Sites",
      icon: "🏛️",
      photo: "https://commons.wikimedia.org/wiki/Special:FilePath/MNCARS%2001.jpg?width=400",
      photoAlt: "Museo Reina Sofía",
    },
    {
      id: "landmarks",
      label: "Landmarks",
      icon: "🌳",
      photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Palacio%20Real%20%28Madrid%29%2001.jpg?width=400",
      photoAlt: "Palacio Real de Madrid",
    },
  ],
  barrios: [
    { id: "all", label: "All" },
    { id: "sol", label: "Sol" },
    { id: "chamberi", label: "Chamberí" },
    { id: "malasana", label: "Malasaña / Chueca" },
    { id: "latina", label: "La Latina" },
    { id: "other", label: "Other" },
  ],
  places: [
    {
      id: "thompson",
      name: "Thompson Madrid",
      category: "stay",
      kind: "landmarks",
      why: "Home base. Walks start here.",
      neighborhood: "Sol / Gran Vía",
      address: "Plaza del Carmen, s/n, 28013 Madrid",
      lat: 40.41857,
      lng: -3.70267,
      takeaway: "Hyatt / Thompson Hotels. Home base — walking notes are from here.",
      link: "https://www.hyatt.com/hotel/spain/thompson-madrid/madrp",
      linkLabel: "Hyatt listing",
      walk: "You are here",
      coordSource: "provided; matches OSM way/265317799",
      hours: "Hours: check site",
    },
    {
      id: "chamberi-market",
      name: "Mercado de Chamberí",
      category: "markets",
      kind: "shopping",
      why: "Working market. Weekday mornings.",
      neighborhood: "Chamberí",
      address: "Calle de Alonso Cano, 10, 28010 Madrid",
      lat: 40.43622,
      lng: -3.69762,
      takeaway: "Working market since 1943: produce, meat, fish, plus a gastro area. Weekday mornings best.",
      use: "Weekday mornings.",
      link: "https://mercadodechamberi.es",
      linkLabel: "mercadodechamberi.es",
      walk: "~2.8 km / ~35 min walk, or Metro",
      shops: [
        {
          name: "Jamonera Castellana",
          note: "Since 1964.",
          link: "https://mercadodechamberi.es/jamonera-castellana",
        },
        {
          name: "Jamonería de Juan",
          note: "Since 1981.",
          link: "https://mercadodechamberi.es/jamoneria-de-juan",
        },
        {
          name: "Casa Tere",
          note: "Mon–Sat mornings typical.",
          link: "https://mercadodechamberi.es/casa-tere",
        },
      ],
      coordSource: "Wikipedia 40.43622222, -3.69761944",
      hours: "Stalls Mon–Fri 9:30–14:00 & 17:00–20:00; Sat 9:30–14:30. Kitchen Tue–Sat lunch + dinner; Sun lunch; Mon closed.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercado%20de%20Chamber%C3%AD%20%28Madrid%29%2001.jpg?width=400",
        alt: "Façade of Mercado de Chamberí",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0 ES",
        page: "https://commons.wikimedia.org/wiki/File:Mercado_de_Chamberí_(Madrid)_01.jpg",
      },
    },
    {
      id: "barcelo",
      name: "Mercado Barceló",
      category: "markets",
      kind: "shopping",
      why: "Modern market. Food upstairs.",
      neighborhood: "Chueca / Justicia (Malasaña edge)",
      address: "Calle de Barceló, 6, 28004 Madrid",
      lat: 40.42681,
      lng: -3.69928,
      takeaway: "Modern rebuild: traditional floors plus upper-level food. Walk and Eat Spain tours use this market.",
      link: "https://mercadobarcelo.es/",
      linkLabel: "mercadobarcelo.es",
      extraLinks: [
        { href: "https://mercadobarcelo.es/puestos-mercado", label: "Stall directory" },
      ],
      walk: "~1.5 km / ~18 min walk",
      shops: [
        {
          name: "Ask for Daniel",
          note: "3rd-generation produce. Stall trade name unpublished.",
        },
        {
          name: "Ask for Gemma",
          note: "Cheese. Stall trade name unpublished.",
        },
        {
          name: "Ask for Roberto",
          note: "Olives. Likely Aceitunas del Campo, puesto 215 — not a published stall name on the tour page.",
        },
      ],
      unnamed:
        "Ham slicer José and Pedro & Carlos’s family tapas bar are unpublished — no invented shop names here.",
      confidence: "confirmed",
      confidenceNote: "Confirmed Walk and Eat market. Vendor first names published; stall trade names unpublished.",
      coordSource: "provided",
      hours: "Floors 0–1 Mon–Fri 9:00–14:30 & 17:30–20:30; Sat 9:00–15:00. Floor 2 food daily 11:00–01:00. Seasonal — check site.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercado-Barcelo-151217.jpg?width=400",
        alt: "Mercado de Barceló",
        credit: "FDV / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Mercado-Barcelo-151217.jpg",
      },
    },
    {
      id: "aceitunas-del-campo",
      name: "Aceitunas del Campo",
      category: "markets",
      kind: "shopping",
      why: "Olive stall inside Barceló.",
      neighborhood: "Mercado Barceló",
      address: "Mercado Barceló, puesto 215, Calle de Barceló, 6, 28004 Madrid",
      lat: 40.42681,
      lng: -3.69928,
      takeaway: "Olive stall inside Barceló. Likely Roberto’s stop on the Walk and Eat market morning.",
      link: "https://mercadobarcelo.es/puestos-mercado",
      linkLabel: "Barceló stall directory",
      walk: "~1.5 km / ~18 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "same building as Mercado Barceló (provided); stall is inside",
      hours: "Hours: check site",
    },
    {
      id: "la-comunal",
      name: "La Comunal",
      category: "food",
      kind: "shopping",
      why: "Olive-oil shop. Go to buy.",
      neighborhood: "Chueca / Justicia",
      address: "Calle de Mejía Lequerica, 1, 28004 Madrid",
      lat: 40.42596,
      lng: -3.69735,
      takeaway:
        "Fundación Patrimonio Comunal Olivarero olive-oil shop. Walk and Eat partner (Óleo Revista, Nov 2024). Mon–Fri 10:00–14:00 & 17:00–20:00, Sat 10:00–14:00; often closed August.",
      link: "https://www.esmadrid.com/en/shopping/comunal",
      linkLabel: "Turismo Madrid",
      walk: "~2.1 km / ~25 min walk",
      confidence: "confirmed",
      confidenceNote: "Confirmed Walk and Eat partner.",
      coordSource: "OSM node Patrimonio Comunal Olivarero /2777281755",
      hours: "Mon–Fri 10:00–14:00 & 17:00–20:00; Sat 10:00–14:00. Often closed August — check site.",
    },
    {
      id: "vallehermoso",
      name: "Mercado de Vallehermoso",
      category: "markets",
      kind: "shopping",
      why: "Local market. Not San Miguel.",
      neighborhood: "Chamberí",
      address: "Calle de Vallehermoso, 36, 28015 Madrid",
      lat: 40.43413,
      lng: -3.70834,
      takeaway: "Framed as a local alternative to San Miguel: working market plus popular food stalls (Tripea among them).",
      link: "https://www.esmadrid.com/compras/mercado-vallehermoso",
      linkLabel: "Turismo Madrid",
      walk: "~2.4 km / ~30 min walk",
      coordSource: "Wikipedia 40.434125, -3.708336",
      hours: "Hours: check site",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercado%20de%20Vallehermoso%20-%20Madrid.jpg?width=400",
        alt: "Mercado de Vallehermoso",
        credit: "Tamorlan / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Mercado_de_Vallehermoso_-_Madrid.jpg",
      },
    },
    {
      id: "mostenses",
      name: "Mercado de los Mostenses",
      category: "markets",
      kind: "shopping",
      why: "Working market behind Gran Vía.",
      neighborhood: "Behind Gran Vía",
      address: "Plaza de los Mostenses, 1, 28015 Madrid",
      lat: 40.42329,
      lng: -3.70906,
      takeaway: "Multicultural working market. CN Traveler called it “anti-posh”; José Andrés has praised the Latin American stalls. Renovated 2024 (Turismo Madrid).",
      link: "https://www.esmadrid.com/compras/mercado-de-los-mostenses",
      linkLabel: "Turismo Madrid",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM relation/4425587",
      hours: "Food Mon–Fri 9:00–14:00 & 17:00–20:00; Sat 9:00–15:00. Hours vary by stall.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercado%20de%20los%20Mostenses%20-%20Madrid%2001.jpg?width=400",
        alt: "Mercado de los Mostenses",
        credit: "Javier Perez Montes / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Mercado_de_los_Mostenses_-_Madrid_01.jpg",
      },
    },
    {
      id: "el-doble",
      name: "El Doble",
      category: "food",
      kind: "food",
      why: "Stand at the bar. Go early.",
      neighborhood: "Chamberí",
      address: "Calle de Ponzano, 58, 28003 Madrid",
      lat: 40.44136,
      lng: -3.69924,
      takeaway: "Standing classic: dobles plus seafood/conservas. Go early. Natural start for a Ponzano evening.",
      use: "Stand at the bar. Go early.",
      link: "https://www.esmadrid.com/restaurantes/el-doble",
      linkLabel: "Turismo Madrid",
      walk: "~2.5 km north / Metro L1 is easier than walking",
      coordSource: "OSM Nominatim for Calle de Ponzano 58",
      hours: "Hours: check site",
    },
    {
      id: "ardosa",
      name: "Bodega de La Ardosa",
      category: "food",
      kind: "food",
      why: "Vermouth and tortilla. Before 7pm.",
      neighborhood: "Malasaña",
      address: "Calle de Colón, 13, 28004 Madrid",
      lat: 40.42377,
      lng: -3.70177,
      takeaway: "Vermú and tortilla. CN Traveler: in all the guides, so tourist influx. Arrive before ~7pm.",
      use: "Stand at the bar. Before ~7pm.",
      link: "https://www.esmadrid.com/en/restaurants/bodega-ardosa",
      linkLabel: "Turismo Madrid",
      walk: "~0.8 km / ~10 min walk",
      tourist: "heavy",
      coordSource: "OSM node Bodega de la Ardosa /2585147466",
      hours: "Sun–Thu 9:00–2:00; Fri–Sat 9:00–2:30",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Bodega%20de%20La%20Ardosa%20(Colón%2013,%20Madrid)%2001.jpg?width=400",
        alt: "Façade of Bodega de La Ardosa",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Bodega_de_La_Ardosa_(Colón_13,_Madrid)_01.jpg",
      },
    },
    {
      id: "casa-baranda",
      name: "Casa Baranda",
      category: "food",
      kind: "food",
      why: "Next door to Ardosa. Go early.",
      neighborhood: "Malasaña",
      address: "Calle de Colón, 11, 28004 Madrid",
      lat: 40.42376,
      lng: -3.70165,
      takeaway: "Ardosa group, next door. Same block, same timing advice.",
      use: "Go early — same block as Ardosa.",
      walk: "~0.8 km / ~10 min walk",
      coordSource: "OSM node Casa Baranda /2661123393",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Casa%20Baranda%20Calle%20de%20Col%C3%B3n%2011%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "casa-julio",
      name: "Casa Julio",
      category: "food",
      kind: "food",
      why: "Croquetas since 1921.",
      neighborhood: "Malasaña",
      address: "Calle de la Madera, 37, 28004 Madrid",
      lat: 40.42431,
      lng: -3.70366,
      takeaway: "Croquetas since 1921.",
      link: "https://www.esmadrid.com/restaurantes/casa-julio",
      linkLabel: "Turismo Madrid",
      walk: "~1 km / ~12 min walk",
      coordSource: "OSM node Casa Julio /2583954354",
      hours: "Hours: check site",
    },
    {
      id: "pez-tortilla",
      name: "Pez Tortilla",
      category: "food",
      kind: "food",
      why: "Tortilla and beer. No reservations.",
      neighborhood: "Malasaña",
      address: "Calle del Pez, 36, 28004 Madrid",
      lat: 40.42425,
      lng: -3.70649,
      takeaway: "Tortillas, croquetas, craft beer. No reservations. This pin is the Malasaña original, not other branches.",
      use: "No reservations.",
      link: "https://peztortilla.com/",
      linkLabel: "peztortilla.com",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM node Pez Tortilla /2630111357",
      hours: "Hours: check site",
    },
    {
      id: "churreria-madrid-1883",
      name: "Churrería Madrid 1883",
      category: "food",
      kind: "food",
      why: "Malasaña churros and chocolate.",
      neighborhood: "Malasaña",
      address: "Calle del Espíritu Santo, 8, 28004 Madrid",
      lat: 40.42514,
      lng: -3.70258,
      takeaway:
        "Malasaña classic for churros and chocolate. Neighborhood vibe match; not proven as Walk and Eat’s first stop.",
      walk: "~1.3 km / ~16 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM node Madrid 1883 Churreria /6325195806",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Churrer%C3%ADa%20Madrid%201883%20Esp%C3%ADritu%20Santo",
      linkLabel: "Google Maps",
    },
    {
      id: "angel-sierra",
      name: "Taberna Ángel Sierra",
      category: "food",
      kind: "food",
      why: "Historic vermouth. Go early.",
      neighborhood: "Plaza Chueca",
      address: "Calle de Gravina, 11, 28004 Madrid",
      lat: 40.42302,
      lng: -3.69746,
      takeaway: "Historic vermouth taberna. Early is easier than peak evening.",
      use: "Go early.",
      link: "https://tabernadeangelsierra.es/",
      linkLabel: "tabernadeangelsierra.es",
      walk: "~1.9 km / ~25 min walk",
      coordSource: "OSM node Taberna de Ángel Sierra /3897299367",
      hours: "Hours: check site",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Escaparate%20de%20la%20Taberna%20de%20Ángel%20Sierra%201.jpg?width=400",
        alt: "Window of Taberna de Ángel Sierra",
        credit: "Uriel1022 / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Escaparate_de_la_Taberna_de_Ángel_Sierra_1.jpg",
      },
    },
    {
      id: "casa-hortensia",
      name: "Casa Hortensia",
      category: "food",
      kind: "food",
      why: "Asturian fabada.",
      neighborhood: "Chueca / Justicia",
      address: "Calle de la Farmacia, 2, 28004 Madrid",
      lat: 40.42387,
      lng: -3.70043,
      takeaway: "Asturian fabada.",
      link: "https://www.esmadrid.com/restaurantes/casa-hortensia",
      linkLabel: "Turismo Madrid",
      walk: "~1 km / ~12 min walk",
      coordSource: "OSM node Casa Hortensia /2661121483",
      hours: "Hours: check site",
    },
    {
      id: "caja-de-cerillas",
      name: "Caja de Cerillas",
      category: "food",
      kind: "food",
      why: "Newer kitchen. Book if you go.",
      neighborhood: "Chamberí",
      address: "Calle de Donoso Cortés, 8, 28015 Madrid",
      lat: 40.43617,
      lng: -3.70547,
      takeaway: "Newer (2025) neo-castizo. Thinner reputation than the old names — book if you go.",
      walk: "~2.4 km / ~30 min walk",
      coordSource: "OSM node Caja De Cerillas /12880638622",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Caja%20de%20Cerillas%20Donoso%20Cort%C3%A9s%208%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "sala-de-despiece",
      name: "Sala de Despiece (SDD1)",
      category: "food",
      kind: "food",
      why: "Theatrical counter. Book ahead.",
      neighborhood: "Chamberí",
      address: "Calle de Alonso Cano, 27–28, 28010 Madrid",
      lat: 40.43757,
      lng: -3.69805,
      takeaway:
        "Theatrical counter. Moved here from Ponzano 11. Likely Culinary Backstreets finale per a visitor writeup.",
      walk: "~3.0 km / ~36 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM building Calle de Alonso Cano 27 way/385080174 (OSM still lists the old Ponzano 11 restaurant node; pin uses the stated new address)",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Sala%20de%20Despiece%20Alonso%20Cano%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "taberna-la-mina",
      name: "Taberna La Mina",
      category: "food",
      kind: "food",
      why: "Old Chamberí taberna since 1949.",
      neighborhood: "Chamberí",
      address: "Calle del General Álvarez de Castro, 8, 28010 Madrid",
      lat: 40.43483,
      lng: -3.70174,
      takeaway: "Founded 1949. Possible Flavours “since 1949” stop — not a slam dunk.",
      walk: "~2.6 km / ~31 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM node Taberna La Mina /2651989201",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Taberna%20La%20Mina%20General%20%C3%81lvarez%20de%20Castro%208%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "comercial",
      name: "Café Comercial",
      category: "food",
      kind: "food",
      why: "Historic café at Bilbao.",
      neighborhood: "Glorieta de Bilbao",
      address: "Glorieta de Bilbao, 7, 28004 Madrid",
      lat: 40.42871,
      lng: -3.70197,
      takeaway: "Historic café. Culinary Backstreets’ Chamberí tour starts here. Mixed “touristy post-reopen” comments.",
      link: "https://www.wheregoesrose.com/madrid-food-tour-culinary-backstreets/",
      linkLabel: "Visitor writeup (wheregoesrose.com)",
      walk: "~2.0 km / ~25 min walk",
      tourist: "soft",
      extraLinks: [
        { href: "https://cafecomercialmadrid.com/", label: "cafecomercialmadrid.com" },
      ],
      coordSource: "OSM node Café Comercial /26065697",
      hours: "Hours: check site",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Caf%C3%A9%20Comercial%20%28Madrid%29%2002.jpg?width=400",
        alt: "Café Comercial",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Café_Comercial_(Madrid)_02.jpg",
      },
    },
    {
      id: "ponzano",
      name: "Calle Ponzano crawl",
      category: "food",
      kind: "food",
      why: "Bar crawl street. Packed weekends.",
      neighborhood: "Chamberí",
      address: "Calle de Ponzano, Chamberí",
      lat: 40.43767,
      lng: -3.69941,
      takeaway: "“Ponzaning”: a corridor of ~70 bars. Crowded Thu–Sat. Start at El Doble if you only do one.",
      use: "Crowded Thu–Sat.",
      walk: "North of Bilbao; Metro L1 toward Ríos Rosas",
      tourist: "soft-weekends",
      coordSource: "OSM way Calle de Ponzano (Almagro stretch) /8029884",
      hours: "Hours: varies by bar",
      link: "https://www.google.com/maps/search/?api=1&query=Calle%20de%20Ponzano%20Chamber%C3%AD%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "anden-0",
      name: "Andén 0 – Estación de Chamberí",
      category: "entertainment",
      kind: "sites",
      why: "Ghost metro museum. Book ahead.",
      neighborhood: "Chamberí",
      address: "Plaza de Chamberí, s/n, 28010 Madrid",
      lat: 40.4323,
      lng: -3.69772,
      takeaway: "Ghost metro museum. Free; book ahead.",
      use: "Book ahead.",
      link: "https://museosmetromadrid.es/estacion-de-chamberi_0/",
      linkLabel: "Museos Metro Madrid",
      walk: "~2.5 km / ~30 min walk",
      coordSource: "Wikipedia 40.4323, -3.69772",
      hours: "Fri 16:00–20:00; Sat 10:00–14:00 & 16:00–20:00; Sun 10:00–14:00. Book ahead. Closed Christmas, New Year, Reyes.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/And%C3%A9n%200%20Estaci%C3%B3n%20de%20Chamber%C3%AD%20en%20septiembre%20de%202022%2001.jpg?width=400",
        alt: "Andén 0, Estación de Chamberí",
        credit: "Emilio J. Rodríguez Posada / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Andén_0_Estación_de_Chamberí_en_septiembre_de_2022_01.jpg",
      },
    },
    {
      id: "beti-jai",
      name: "Frontón Beti Jai",
      category: "entertainment",
      kind: "sites",
      why: "1894 pelota court. Free.",
      neighborhood: "Chamberí / Almagro",
      address: "Calle del Marqués del Riscal, 7, 28010 Madrid",
      lat: 40.43067,
      lng: -3.69116,
      takeaway: "1894 pelota court. National Monument.",
      walk: "~2.3 km / ~28 min walk",
      coordSource: "provided; OSM way/965335844 nearby",
      hours: "Tue–Sun; summer (15 Jun–30 Sep) 10:00–18:00; rest of year 10:00–14:00. Free. Check site.",
      link: "https://www.esmadrid.com/informacion-turistica/fronton-beti-jai",
      linkLabel: "Turismo Madrid",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Front%C3%B3n%20Beti%20Jai%20de%20Madrid%20en%20octubre%20de%202023%2001.jpg?width=400",
        alt: "Frontón Beti Jai",
        credit: "Emilio J. Rodríguez Posada / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Frontón_Beti_Jai_de_Madrid_en_octubre_de_2023_01.jpg",
      },
    },
    {
      id: "sorolla",
      name: "Museo Sorolla",
      category: "entertainment",
      kind: "sites",
      why: "Closed for expansion. Skip it.",
      neighborhood: "Chamberí / Almagro",
      address: "Paseo del General Martínez Campos, 37, 28010 Madrid",
      lat: 40.4354,
      lng: -3.69254,
      takeaway: "Temporarily closed since October 2024 for expansion. Do not plan a visit.",
      link: "https://www.madrid.es/portales/munimadrid/es/Inicio/Cultura-ocio-y-deporte/Cultura-y-ocio/Direcciones-y-telefonos/Museo-Sorolla/",
      linkLabel: "Ayuntamiento de Madrid",
      closed: true,
      coordSource: "Wikipedia 40.435404, -3.692539",
      hours: "Closed (expansion). Check site for reopening.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Museo%20Sorolla%20(Madrid)%2001.jpg?width=400",
        alt: "Façade of Museo Sorolla",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Museo_Sorolla_(Madrid)_01.jpg",
      },
    },
    {
      id: "geominero",
      name: "Museo Geominero",
      category: "entertainment",
      kind: "sites",
      why: "Free geology museum. Mornings.",
      neighborhood: "Chamberí",
      address: "Calle de Ríos Rosas, 23, 28003 Madrid",
      lat: 40.4427,
      lng: -3.6996,
      takeaway: "Free geology museum. Open mornings.",
      link: "https://www.igme.es/museo/visitanos/",
      linkLabel: "IGME – Visítanos",
      walk: "Near El Doble / Ríos Rosas Metro",
      coordSource: "Wikipedia 40.4427, -3.6996",
      hours: "Daily 9:00–14:00, including holidays. Closed 24–25 & 31 Dec, 1 & 6 Jan. Free.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Museo%20Geominero%20-%20main%20hall%20-%20Madrid%20Spain%2001.jpg?width=400",
        alt: "Main hall of Museo Geominero",
        credit: "PePeEfe / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Museo_Geominero_-_main_hall_-_Madrid_Spain_01.jpg",
      },
    },
    {
      id: "olavide",
      name: "Plaza de Olavide",
      category: "entertainment",
      kind: "landmarks",
      why: "Local plaza. A pause, not a sight.",
      neighborhood: "Chamberí",
      address: "Plaza de Olavide, 28010 Madrid",
      lat: 40.43305,
      lng: -3.7006,
      takeaway: "Local octagonal plaza with terraces. A pause, not a monument.",
      walk: "~2.2 km / ~27 min walk",
      coordSource: "OSM way Plaza de Olavide /248905968",
      hours: "Open plaza",
      link: "https://www.google.com/maps/search/?api=1&query=Plaza%20de%20Olavide%20Madrid",
      linkLabel: "Google Maps",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20la%20Plaza%20de%20Olavide%20de%20Madrid.jpg?width=400",
        alt: "Plaza de Olavide",
        credit: "Jotaemec / Wikimedia Commons",
        license: "CC0",
        page: "https://commons.wikimedia.org/wiki/File:Vista_de_la_Plaza_de_Olavide_de_Madrid.jpg",
      },
    },
    {
      id: "canal",
      name: "Teatros del Canal",
      category: "entertainment",
      kind: "sites",
      why: "Shows. Check the calendar.",
      neighborhood: "Chamberí",
      address: "Calle de Cea Bermúdez, 1, 28003 Madrid",
      lat: 40.43844,
      lng: -3.70506,
      takeaway: "Performing arts. Check the calendar if you want a show.",
      link: "https://www.teatroscanal.com/",
      linkLabel: "teatroscanal.com",
      walk: "~2.7 km / ~35 min walk",
      coordSource: "Wikipedia 40.438441, -3.705059",
      hours: "Hours: check site",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Teatros%20del%20Canal%20(Madrid)%2001.jpg?width=400",
        alt: "Teatros del Canal",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Teatros_del_Canal_(Madrid)_01.jpg",
      },
    },
    {
      id: "conde-duque",
      name: "Centro Cultural Conde Duque",
      category: "entertainment",
      kind: "sites",
      why: "Old barracks. Exhibitions and courtyard.",
      neighborhood: "Malasaña / Conde Duque",
      address: "Calle del Conde Duque, 9–11, 28015 Madrid",
      lat: 40.42785,
      lng: -3.71068,
      takeaway: "Municipal cultural centre in the old barracks. Exhibitions, concerts, courtyard.",
      walk: "~1.8 km / ~22 min walk",
      coordSource: "Wikipedia 40.427852, -3.710681",
      hours: "Hours: check site",
      link: "https://www.condeduquemadrid.es/",
      linkLabel: "condeduquemadrid.es",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuartel%20del%20Conde-Duque%20%28Madrid%29%2005.jpg?width=400",
        alt: "Conde Duque",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Cuartel_del_Conde-Duque_(Madrid)_05.jpg",
      },
    },
    {
      id: "historia",
      name: "Museo de Historia de Madrid",
      category: "entertainment",
      kind: "sites",
      why: "City history. Good rainy hour.",
      neighborhood: "Malasaña",
      address: "Calle de Fuencarral, 78, 28004 Madrid",
      lat: 40.42579,
      lng: -3.70076,
      takeaway: "City history museum on Fuencarral. Useful rainy-hour stop.",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM node Museo de Historia de Madrid /12921081474",
      hours: "Tue–Sun 10:00–20:00; summer (15 Jun–15 Sep) 10:00–19:00. Closed Mon and 1 & 6 Jan, 1 May, 24–25 & 31 Dec. Free.",
      link: "https://www.esmadrid.com/informacion-turistica/museo-de-historia",
      linkLabel: "Turismo Madrid",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Madrid%20-%20Museo%20de%20Historia%20de%20Madrid%20(36765266065).jpg?width=400",
        alt: "Museo de Historia de Madrid on Fuencarral",
        credit: "Fred Romero / Wikimedia Commons",
        license: "CC BY 2.0",
        page: "https://commons.wikimedia.org/wiki/File:Madrid_-_Museo_de_Historia_de_Madrid_(36765266065).jpg",
      },
    },
    {
      id: "escultura",
      name: "Museo de Escultura al Aire Libre",
      category: "entertainment",
      kind: "sites",
      why: "Free outdoor sculptures. Always open.",
      neighborhood: "Castellana / Rubén Darío",
      address: "Paseo de la Castellana, 40, 28046 Madrid",
      lat: 40.43303,
      lng: -3.68748,
      takeaway: "Free outdoor sculpture under the Juan Bravo overpass, near Rubén Darío.",
      link: "https://www.esmadrid.com/informacion-turistica/museo-escultura-aire-libre-castellana",
      linkLabel: "Turismo Madrid",
      walk: "~2.5 km / ~30 min walk",
      coordSource: "Wikipedia 40.43303, -3.68748",
      hours: "Open-air — always open",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Madrid%20-%20Museo%20de%20Escultura%20al%20aire%20libre%20de%20La%20Castellana%2005.JPG?width=400",
        alt: "Museo de Escultura al Aire Libre",
        credit: "Zarateman / Wikimedia Commons",
        license: "CC0",
        page: "https://commons.wikimedia.org/wiki/File:Madrid_-_Museo_de_Escultura_al_aire_libre_de_La_Castellana_05.JPG",
      },
    },
    {
      id: "gran-via",
      name: "Gran Vía / Teatro district walk",
      category: "entertainment",
      kind: "landmarks",
      why: "Evening lights. Short walk from home.",
      neighborhood: "Sol / Gran Vía",
      address: "Plaza de Callao / Gran Vía",
      lat: 40.41986,
      lng: -3.70581,
      takeaway: "Theatre stretch of Gran Vía. Short walk from Thompson — evening lights, not a hidden corner.",
      walk: "~0.5 km / a few minutes",
      coordSource: "OSM Plaza de Callao relation/13452454",
      hours: "Street — always open",
      link: "https://www.esmadrid.com/informacion-turistica/gran-via",
      linkLabel: "Turismo Madrid",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Gran%20V%C3%ADa%20%28Madrid%29%2039.jpg?width=400",
        alt: "Gran Vía, Madrid",
        credit: "ianaiare / Wikimedia Commons",
        license: "CC BY-SA 2.0",
        page: "https://commons.wikimedia.org/wiki/File:Gran_Vía_(Madrid)_39.jpg",
      },
    },
    {
      id: "cava-baja",
      name: "Cava Baja / La Latina",
      category: "food",
      kind: "food",
      why: "Tapas street. Evening crawl.",
      neighborhood: "La Latina",
      address: "Calle de la Cava Baja, 28005 Madrid",
      lat: 40.41236,
      lng: -3.70925,
      takeaway:
        "The tapas street — a crawl, not one restaurant. Popular, still the local evening strip. Not Mercado San Miguel.",
      use: "Evening tapas crawl. Sunday lunch after El Rastro.",
      link: "https://www.esmadrid.com/en/madrid-neighbourhoods/latina",
      linkLabel: "Turismo Madrid",
      walk: "~1.2 km / ~16 min walk",
      tourist: "soft-weekends",
      coordSource: "OSM way Calle de la Cava Baja /4519457",
      hours: "Hours: varies by bar",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Fiestas%20de%20la%20Paloma%202023%20-%20Calle%20de%20la%20Cava%20Baja%20-%20Madrid%2007.jpg?width=400",
        alt: "Calle de la Cava Baja, La Latina",
        credit: "Javier Pérez Montes / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Fiestas_de_la_Paloma_2023_-_Calle_de_la_Cava_Baja_-_Madrid_07.jpg",
      },
    },
    {
      id: "riu-360",
      name: "360° Sky Bar – Hotel Riu Plaza España",
      category: "entertainment",
      kind: "sites",
      why: "Sunset rooftop. Ticket for non-guests.",
      neighborhood: "Sol / Gran Vía",
      address: "Gran Vía 84 / Calle del Maestro Guerrero, s/n, 28013 Madrid",
      lat: 40.4242,
      lng: -3.71103,
      takeaway:
        "Tourist sunset rooftop in Edificio España. One ticket covers floor-26 Sky Bar (indoor), floor-27 terrace, and El Edén. Drinks and food. Non-guests pay; hotel guests usually free.",
      use: "Sunset. Book/ticket ahead if required.",
      link: "https://www.riu360rooftopbar.com/en/",
      linkLabel: "riu360rooftopbar.com",
      extraLinks: [
        { href: "https://www.riu.com/blog/en/riu-plaza-espana-terrace-faq/", label: "RIU terrace FAQ" },
      ],
      walk: "~1.3 km / ~16 min walk",
      tourist: "heavy",
      coordSource: "OSM way Hotel Riu Plaza España /1432522463",
      hours:
        "Sky Bar daily 12:00–3:00, kitchen 12:00–00:30. Rooftop daily 11:00–2:00, kitchen 12:00–23:30, last entry midnight. Non-guests: Mon–Fri €5 before 17:00, €10 after; Sat/Sun/holidays €10. Guests usually free.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Madrid%20-%20Hotel%20Riu%20Plaza%20Espa%C3%B1a%204.jpg?width=400",
        alt: "Hotel Riu Plaza España, Edificio España",
        credit: "Zarateman / Wikimedia Commons",
        license: "CC0",
        page: "https://commons.wikimedia.org/wiki/File:Madrid_-_Hotel_Riu_Plaza_España_4.jpg",
      },
    },
    {
      id: "palacio-real",
      name: "Palacio Real",
      category: "entertainment",
      kind: "landmarks",
      why: "Royal palace. Book timed tickets.",
      rating: { score: 4.7, source: "Google", asOf: "2026-08" },
      neighborhood: "Austrias",
      address: "Calle de Bailén, s/n, 28013 Madrid",
      lat: 40.41674,
      lng: -3.71362,
      takeaway:
        "The big royal-palace circuit. Timed tickets sell out. Access currently via the Bailén / Requena arch (renovation — Turismo Madrid, Aug 2026).",
      use: "Book timed entry. Pair with Cava Baja / La Latina after if walking south.",
      link: "https://tickets.patrimonionacional.es/en/tickets/palacio-real-de-madrid",
      linkLabel: "Patrimonio Nacional tickets",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/tourist-information/royal-palace", label: "Turismo Madrid" },
      ],
      walk: "~1.3 km / ~17 min walk",
      tourist: "heavy",
      coordSource: "OSM node Palacio Real de Madrid /4451986389",
      hours:
        "Winter (Oct–Mar) Mon–Sat 10:00–18:00, Sun 10:00–16:00. Summer (Apr–Sep) Mon–Sat 10:00–19:00, Sun 10:00–16:00. Last entry 1 hour before close. Closed 1 & 6 Jan, 1 May, 25 Dec; early close 24 & 31 Dec. Official events can shut it.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Palacio%20Real%20%28Madrid%29%2001.jpg?width=400",
        alt: "Palacio Real de Madrid",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Palacio_Real_(Madrid)_01.jpg",
      },
    },
    {
      id: "retiro",
      name: "Parque del Retiro",
      category: "entertainment",
      kind: "landmarks",
      why: "Free park. Walk the lake.",
      rating: { score: 4.8, count: 209159, source: "Google", asOf: "2026-08" },
      neighborhood: "Retiro",
      address: "Plaza de la Independencia, 7, 28001 Madrid",
      lat: 40.41981,
      lng: -3.68827,
      takeaway:
        "Pin is the Plaza de la Independencia / Puerta de Alcalá gate (Retiro metro). Free park. Walk the lake. Palacio de Cristal is closed for works; Palacio de Velázquez reopened 24 Jun 2026 — check the museum calendar.",
      use: "Walk, lake, Palacio de Velázquez if open. Palacio de Cristal closed for restoration.",
      link: "https://www.esmadrid.com/informacion-turistica/parque-del-retiro",
      linkLabel: "Turismo Madrid",
      extraLinks: [
        { href: "https://www.museoreinasofia.es/en/visit/opening-times/", label: "Reina Sofía (Retiro palaces)" },
      ],
      walk: "~1.6 km / ~22 min walk",
      tourist: "soft",
      coordSource: "OSM Plaza de la Independencia (Jerónimos) way/43405580; Ayuntamiento address Plaza Independencia 7",
      hours: "Apr–Sep 6:00–00:00; Oct–Mar 6:00–22:00. Free. Weather alerts can close gates.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Estanque%20del%20Retiro%2C%20Parque%20del%20Retiro%2C%20Madrid%2C%20Espa%C3%B1a%2C%202017-05-18%2C%20DD%2016.jpg?width=400",
        alt: "Estanque Grande, Parque del Retiro",
        credit: "Diego Delso / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Estanque_del_Retiro,_Parque_del_Retiro,_Madrid,_España,_2017-05-18,_DD_16.jpg",
      },
    },
    {
      id: "reina-sofia",
      name: "Museo Reina Sofía",
      category: "entertainment",
      kind: "sites",
      why: "Guernica is the reason.",
      rating: { score: 4.5, count: 65345, source: "Google", asOf: "2026-08" },
      neighborhood: "Paseo del Arte",
      address: "Calle de Santa Isabel, 52, 28012 Madrid",
      lat: 40.40805,
      lng: -3.69442,
      takeaway:
        "Guernica is the reason. Prado is next door if you have a second museum day — not required. Free evening window is a crush.",
      use: "Closed Tuesday. Guernica is the target. Free evening window is packed.",
      link: "https://www.museoreinasofia.es/en/visit/opening-times/",
      linkLabel: "museoreinasofia.es",
      walk: "~1.8 km / ~25 min walk, or Metro",
      tourist: "heavy",
      coordSource: "OSM way Museo Nacional Centro de Arte Reina Sofía /991444051",
      hours:
        "Mon + Wed–Sat 10:00–21:00; Sun 10:00–14:30; closed Tue. Free last two hours (Mon/Wed–Sat 19:00–21:00; Sun 12:30–14:30) — still need a ticket. Last entry 30 min before close. General €12.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/MNCARS%2001.jpg?width=400",
        alt: "Museo Reina Sofía",
        credit: "Juan Lupión / Wikimedia Commons",
        license: "CC BY 2.0",
        page: "https://commons.wikimedia.org/wiki/File:MNCARS_01.jpg",
      },
    },
    {
      id: "el-rastro",
      name: "El Rastro",
      category: "markets",
      kind: "shopping",
      why: "Sunday flea crush. Go early.",
      neighborhood: "La Latina",
      address: "Plaza de Cascorro / Calle de Ribera de Curtidores, 28012 Madrid",
      lat: 40.41058,
      lng: -3.70732,
      takeaway:
        "Sunday flea market from Cascorro down Ribera de Curtidores. Midday is a crush. Pin is Plaza de Cascorro.",
      use: "Sunday morning. Go early. Pair with Cava Baja lunch.",
      link: "https://www.esmadrid.com/en/shopping/el-rastro",
      linkLabel: "Turismo Madrid",
      walk: "~1.3 km / ~17 min walk",
      tourist: "heavy",
      coordSource: "OSM way Plaza de Cascorro /335204867",
      hours: "Sun and public holidays 9:00–15:00. First Saturday of the month (except Jul, Aug, Nov) has a separate antiques fair — check site.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Rastro%20-%20Plaza%20de%20Cascorro%20-%20Madrid%2002.jpg?width=400",
        alt: "El Rastro at Plaza de Cascorro",
        credit: "Javier Perez Montes / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Rastro_-_Plaza_de_Cascorro_-_Madrid_02.jpg",
      },
    },
    {
      id: "la-duquesita",
      name: "La Duquesita",
      category: "food",
      kind: "shopping",
      why: "1914 pastry shop. Buy to take.",
      neighborhood: "Salesas / Chueca",
      address: "Calle de Fernando VI, 2, 28004 Madrid",
      lat: 40.4256807,
      lng: -3.6969664,
      takeaway:
        "1914 pastry shop, now Oriol Balaguer. Croissants and Tarta Duquesita get mentioned on Turismo Madrid. Well known — not a hidden bakery.",
      use: "Pastry / tea room. Good any day; not on the Sunday Rastro walk (wrong direction).",
      link: "https://laduquesita.es/",
      linkLabel: "laduquesita.es",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/shopping/la-duquesita", label: "Turismo Madrid" },
      ],
      walk: "~1.2 km / ~15 min walk, Metro Alonso Martínez",
      tourist: "soft",
      coordSource: "OSM node Pastelería La Duquesita /4763918423",
      hours: "Daily 9:00–20:30 (Turismo Madrid, Apr 2026). Check laduquesita.es.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/La%20Duquesita-%20Exterior%20(323354129).jpg?width=400",
        alt: "Exterior of La Duquesita",
        credit: "deramaenrama / Wikimedia Commons",
        license: "CC BY 2.0",
        page: "https://commons.wikimedia.org/wiki/File:La_Duquesita-_Exterior_(323354129).jpg",
      },
    },
    {
      id: "cebada",
      name: "Mercado de la Cebada",
      category: "markets",
      kind: "shopping",
      why: "La Latina market hall.",
      neighborhood: "La Latina",
      address: "Plaza de la Cebada, s/n, 28005 Madrid",
      lat: 40.4110938,
      lng: -3.7098246,
      takeaway:
        "La Latina market hall. Regular Sunday is not a given — only the first Sunday plus posted open Sundays/holidays. MadriZebada outdoor market is first Sunday except August (check the agenda).",
      use: "La Latina market hall. Pair with El Rastro only if it’s a first Sunday or an advertised open Sunday.",
      link: "https://www.mercadodelacebada.com/",
      linkLabel: "mercadodelacebada.com",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/shopping/cebada-market", label: "Turismo Madrid" },
        { href: "https://www.mercadodelacebada.com/mercado/", label: "2026 hours" },
      ],
      walk: "~1.3 km / ~17 min walk, or Metro La Latina (L5)",
      coordSource: "OSM way Mercado de la Cebada /4346296",
      hours:
        "Stalls Mon–Fri 9:00–14:00 & 17:30–20:30; Sat 9:00–18:00. First Sunday 11:00–17:00. Other open Sundays/holidays 11:00–17:00 — not every Sunday; check the 2026 list. MadriZebada (first Sun except Aug) ~12:00–17:00. Hours vary by stall.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Madrid%20-%20Mercado%20de%20la%20Cebada%20-%20outside.jpg?width=400",
        alt: "Outside Mercado de la Cebada",
        credit: "Tiia Monto / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Madrid_-_Mercado_de_la_Cebada_-_outside.jpg",
      },
    },
    {
      id: "campo-del-moro",
      name: "Campo del Moro",
      category: "entertainment",
      kind: "landmarks",
      why: "Free gardens behind the palace.",
      rating: { score: 4.6, count: 9114, source: "Google", asOf: "2025-07" },
      neighborhood: "Austrias / palace",
      address: "Paseo de la Virgen del Puerto, s/n, 28005 Madrid",
      lat: 40.4180757,
      lng: -3.717772,
      takeaway:
        "Free gardens directly behind the Royal Palace. Fewer people than the palace rooms. Weather and official events can close it.",
      use: "Free gardens after or instead of the palace tour.",
      link: "https://www.esmadrid.com/informacion-turistica/campo-del-moro",
      linkLabel: "Turismo Madrid",
      extraLinks: [
        { href: "https://www.patrimonionacional.es/visita/jardines-del-campo-del-moro", label: "Patrimonio Nacional" },
      ],
      walk: "~1.7 km / ~21 min walk. Gates: Virgen del Puerto, Cuesta de San Vicente, Cuesta de la Vega.",
      tourist: "soft",
      coordSource: "OSM relation Campo del Moro /1505193",
      hours:
        "Free. Closed 1 Jan, 1 May, 25 Dec; official events / weather can shut it. Virgen del Puerto: Oct–Mar 10:00–18:00; Apr & Sep 10:00–21:00; May–Aug 10:00–22:00. Cuesta de San Vicente: Apr–Sep 10:00–20:00; Oct–Mar 10:00–18:00. Cuesta de la Vega: daily 10:00–20:00. Turismo Madrid, Jan 2026 — check before you go.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Campo%20del%20Moro%20(Madrid)%2004.jpg?width=400",
        alt: "Campo del Moro gardens with the Royal Palace",
        credit: "Bjaglin / Wikimedia Commons",
        license: "CC BY 2.0",
        page: "https://commons.wikimedia.org/wiki/File:Campo_del_Moro_(Madrid)_04.jpg",
      },
    },
    {
      id: "thyssen",
      name: "Museo Thyssen-Bornemisza",
      category: "entertainment",
      kind: "sites",
      why: "Art museum. Lighter than Prado.",
      neighborhood: "Paseo del Arte",
      address: "Paseo del Prado, 8, 28014 Madrid",
      lat: 40.4162159,
      lng: -3.6949317,
      takeaway:
        "Paseo del Prado art museum. Usually lighter than the Prado rooms. Permanent collection plus temps. Monday afternoon is the free window.",
      use: "Art museum. Fewer crowds than Prado. Pair with Retiro / Reina Sofía if doing the museum mile.",
      link: "https://www.museothyssen.org/en/visit/opening-hours-prices",
      linkLabel: "museothyssen.org",
      extraLinks: [
        { href: "https://www.museothyssen.org/en", label: "Tickets / home" },
      ],
      walk: "~0.9 km / ~12 min walk",
      tourist: "soft",
      coordSource: "OSM relation Museo Thyssen-Bornemisza /1869336",
      hours:
        "Mon 12:00–16:00 (free collection; no ticket). Tue–Fri + Sun 10:00–19:00 (1 Jul–31 Aug Tue–Fri to 21:00). Sat 10:00–23:00 (temps free 21:00–23:00). Last entry 30 min before close. Closed 1 Jan, 1 May, 25 Dec; 24 & 31 Dec 10:00–15:00. General €14. Check site.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Museo%20Thyssen-Bornemisza%20(Madrid)%2006a.jpg?width=400",
        alt: "Museo Thyssen-Bornemisza, Palacio de Villahermosa",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Museo_Thyssen-Bornemisza_(Madrid)_06a.jpg",
      },
    },
    {
      id: "botanico",
      name: "Real Jardín Botánico",
      category: "entertainment",
      kind: "landmarks",
      why: "Ticketed garden next to Prado.",
      neighborhood: "Paseo del Arte",
      address: "Plaza de Murillo, 2, 28014 Madrid",
      lat: 40.4114871,
      lng: -3.6906894,
      takeaway:
        "Ticketed CSIC garden next to Prado / Retiro. Tuesday morning has a free window — official and Turismo cutoffs disagree, so check rjb.csic.es.",
      use: "Paid garden next to Prado. Good after Retiro.",
      link: "https://rjb.csic.es/el-jardin/guia-practica/",
      linkLabel: "rjb.csic.es",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/tourist-information/royal-botanic-gardens", label: "Turismo Madrid" },
        { href: "https://entradas.rjb.csic.es", label: "Tickets" },
      ],
      walk: "~1.7 km / ~21 min walk",
      tourist: "soft",
      coordSource: "OSM way Royal Botanical Garden of Madrid /15244804",
      hours:
        "Daily from 10:00. Close Nov–Feb 18:00; Mar & Oct 19:00; Apr & Sep 20:00; May–Aug 21:00. Last entry 30 min before. Closed 1 Jan and 25 Dec. Tue morning free — check site (listings disagree on the cutoff). Gardens €4 (Turismo Madrid, Mar 2026).",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Real%20Jard%C3%ADn%20Bot%C3%A1nico%2C%20Madrid%2C%20Espa%C3%B1a%2C%202017-05-18%2C%20DD%2038.jpg?width=400",
        alt: "Real Jardín Botánico, Madrid",
        credit: "Diego Delso / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Real_Jardín_Botánico,_Madrid,_España,_2017-05-18,_DD_38.jpg",
      },
    },
    {
      id: "juana-la-loca",
      name: "Juana La Loca",
      category: "food",
      kind: "food",
      why: "Famous tortilla. Book or go early.",
      neighborhood: "Recoletos / Paseo del Arte",
      address: "Calle de Recoletos, 10, 28001 Madrid",
      lat: 40.4218737,
      lng: -3.6902566,
      takeaway:
        "Visitor-tested favorite. Creative tapas; the tortilla is the one people talk about. Moved here from Plaza Puerta de Moros / La Latina — no longer on the Sunday Cava Baja walk. Book or go early.",
      use: "Book or go early. Famous tortilla.",
      link: "https://www.esmadrid.com/en/restaurants/juana-loca",
      linkLabel: "Turismo Madrid",
      extraLinks: [
        { href: "https://www.juanalalocaes.com/book-a-table", label: "Book a table" },
      ],
      walk: "~1.1 km / ~13 min walk",
      tourist: "soft",
      coordSource: "OSM node Juana La Loca /10574429709",
      hours: "Daily 13:00–17:00 & 20:00–24:00 (Turismo Madrid, Nov 2025). Check site.",
    },
    {
      id: "botin",
      name: "Sobrino de Botín",
      category: "food",
      kind: "food",
      why: "Oldest restaurant. Book the pig.",
      neighborhood: "Plaza Mayor / Austrias",
      address: "Calle de los Cuchilleros, 17, 28005 Madrid",
      lat: 40.4141745,
      lng: -3.707981,
      takeaway:
        "Visitor-tested favorite. Guinness oldest restaurant (1725). Castilian roast — suckling pig from the original oven. Tourist-heavy; book.",
      use: "Book. Suckling pig.",
      link: "https://botin.es/",
      linkLabel: "botin.es",
      extraLinks: [
        { href: "https://botin.es/en/contacto-botin/", label: "Hours / contact" },
      ],
      walk: "~0.7 km / ~8 min walk",
      tourist: "heavy",
      coordSource: "OSM node Botín /510812824",
      hours: "Daily lunch 13:00–16:00, dinner 20:00–24:00 (botin.es).",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Casa%20Bot%C3%ADn-Madrid-2009.jpg?width=400",
        alt: "Façade of Sobrino de Botín",
        credit: "Tamorlan / Wikimedia Commons",
        license: "CC BY 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Casa_Botín-Madrid-2009.jpg",
      },
    },
    {
      id: "chocolateria-1902",
      name: "Chocolatería 1902",
      category: "food",
      kind: "food",
      why: "Churros. Quieter than San Ginés.",
      neighborhood: "Sol / Gran Vía",
      address: "Calle de San Martín, 2, 28013 Madrid",
      lat: 40.417628,
      lng: -3.7069147,
      takeaway:
        "Visitor-tested favorite. Family churrería (Los Artesanos 1902 / Fábrica 1902). They make the chocolate themselves from three cacaos. Eat-in is this centro shop. One block from San Ginés, usually quieter.",
      use: "Churros + thick chocolate. Quieter than San Ginés.",
      link: "https://chocolateria1902.com/",
      linkLabel: "chocolateria1902.com",
      walk: "~0.4 km / ~5 min walk",
      tourist: "soft",
      coordSource: "OSM node Los Artesanos 1902 /2656003471",
      hours: "Typically daily ~7:00–23:00 (directories; official site does not list hours). Check chocolateria1902.com.",
    },
    {
      id: "revoltosa-prado",
      name: "Revoltosa Prado",
      category: "food",
      kind: "food",
      why: "Huevos rotos near the Prado.",
      neighborhood: "Paseo del Arte / Huertas",
      address: "Calle del Prado, 4, 28014 Madrid",
      lat: 40.4145549,
      lng: -3.6997005,
      takeaway:
        "Taberna near the Prado. Castizo raciones — huevos rotos and octopus turn up on the menu. Morning coffee through late drinks.",
      use: "Huevos rotos / raciones near Prado.",
      link: "https://www.revoltosamadrid.com/prado/",
      linkLabel: "revoltosamadrid.com",
      walk: "~0.5 km / ~6 min walk",
      coordSource: "OSM node Revoltosa /11867250770",
      hours:
        "Mon–Wed 9:30–1:00; Thu 9:30–1:30; Fri 9:30–2:00; Sat from 11:00 or 12:00 to 2:00; Sun from 11:00 or 12:00 to 1:00 (site pages disagree on Sat/Sun open). Check revoltosamadrid.com.",
    },
    {
      id: "tortilla-castiza",
      name: "La Tortilla Castiza",
      category: "food",
      kind: "food",
      why: "Tortilla to go. Sunday pintxos.",
      neighborhood: "El Rastro / Embajadores",
      address: "Calle de la Ribera de Curtidores, 26, local 16, 28005 Madrid",
      lat: 40.4066533,
      lng: -3.7073755,
      takeaway:
        "Tortilla specialist on Ribera de Curtidores. Weekdays are takeaway and delivery; Sunday they run a pintxo bar for El Rastro (El Pintxódromo).",
      use: "Tortilla to go. Sunday pintxos at the Rastro.",
      link: "https://www.latortillacastiza.com/",
      linkLabel: "latortillacastiza.com",
      walk: "~1.4 km / ~17 min walk",
      coordSource: "OSM node La Tortilla Castiza /12196594554",
      hours: "Closed Mon–Tue. Wed–Fri 13:00–22:30; Sat–Sun 13:00–16:00 (latortillacastiza.com). Eat-in mainly Sunday.",
    },
    {
      id: "casa-carola",
      name: "Casa Carola",
      category: "food",
      kind: "food",
      why: "Lunch-only cocido. Book ahead.",
      neighborhood: "Salamanca / Lista",
      address: "Calle de Padilla, 54, 28006 Madrid",
      lat: 40.4311455,
      lng: -3.6775753,
      takeaway:
        "Traditional three-vuelco cocido, lunch only, set menu. Book. Closed mid-June to mid-September — seasonal, not a permanent shutdown.",
      use: "Book. Lunch-only cocido. Closed mid-June–mid-September.",
      link: "https://www.casacarola.com/",
      linkLabel: "casacarola.com",
      walk: "~2.5 km / ~31 min walk, or Metro Lista",
      coordSource: "OSM node Casa Carola /8676589690",
      hours:
        "Lunch daily 13:00–16:00. Closed mid-June to mid-September (casacarola.com). Book.",
    },
    {
      id: "julian-tolosa",
      name: "Casa Julián de Tolosa",
      category: "food",
      kind: "food",
      why: "Basque steak. Book. Pricey.",
      neighborhood: "Ibiza / Retiro",
      address: "Calle de Ibiza, 39, 28009 Madrid",
      lat: 40.4182946,
      lng: -3.6734939,
      takeaway:
        "Basque grill — steak, piquillo peppers, cheesecake. Pricey. This pin is the Ibiza branch, not Cava Baja.",
      use: "Book. Basque steak; pricey.",
      link: "https://ibiza.juliandetolosa.com/",
      linkLabel: "ibiza.juliandetolosa.com",
      walk: "~2.5 km / ~30 min walk, or Metro Ibiza",
      tourist: "soft",
      coordSource: "OSM node Calle de Ibiza 39 /2681481545",
      hours: "Mon–Sat 13:30–16:00 & 20:30–24:00; Sun 13:30–16:00 (official Ibiza page).",
    },
    {
      id: "honest-greens-gran-via",
      name: "Honest Greens Gran Vía 52",
      category: "food",
      kind: "food",
      why: "Simple healthy bowls near the hotel.",
      neighborhood: "Sol / Gran Vía",
      address: "Gran Vía, 52, 28013 Madrid",
      lat: 40.4211146,
      lng: -3.70687,
      takeaway:
        "Local healthy-bowl chain. This pin is Gran Vía 52 only — other branches are skipped. Near the hotel if you want a simple plate.",
      use: "Healthy bowls. This branch only.",
      link: "https://www.honestgreens.com/",
      linkLabel: "honestgreens.com",
      walk: "~0.5 km / ~6 min walk",
      coordSource: "OSM node Gran Vía 52 /6553934903 (building; restaurant is inside)",
      hours: "Hours: check site",
    },
    {
      id: "taberna-laredo",
      name: "Taberna Laredo",
      category: "food",
      kind: "food",
      why: "Market tapas. Book the dining room.",
      neighborhood: "Ibiza / Doctor Castelo",
      address: "Calle del Doctor Castelo, 30, 28009 Madrid",
      lat: 40.4202174,
      lng: -3.6751795,
      takeaway:
        "Upscale market tapas east of Retiro. Book the dining room; bar and terrace are walk-in. Phone bookings only through official channels — fake reservation sites exist.",
      use: "Book the dining room. Bar is walk-in.",
      link: "https://tabernalaredo.com/",
      linkLabel: "tabernalaredo.com",
      extraLinks: [
        { href: "https://www.esmadrid.com/restaurantes/laredo", label: "Turismo Madrid" },
      ],
      walk: "~2.3 km / ~28 min walk, or Metro Ibiza",
      coordSource: "OSM node Taberna Laredo /8833727217",
      hours: "Mon–Sat 13:15–24:30; Sun closed (Turismo Madrid, Aug 2023). Check site.",
    },
    {
      id: "tasca-retiro",
      name: "La Tasca del Retiro",
      category: "food",
      kind: "food",
      why: "Oxtail and salmorejo by Retiro.",
      neighborhood: "Retiro / Ibiza",
      address: "Avenida de Menéndez Pelayo, 11, 28009 Madrid",
      lat: 40.4206337,
      lng: -3.6794004,
      takeaway:
        "Same Ibiza / Retiro strip as Laredo, on Menéndez Pelayo rather than Doctor Castelo. Seasonal Spanish and Basque plates — oxtail and salmorejo show up often.",
      use: "Oxtail / salmorejo. Book if you want a table.",
      link: "https://latascadelretiro.es/",
      linkLabel: "latascadelretiro.es",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/restaurants/tasca-retiro", label: "Turismo Madrid" },
      ],
      walk: "~2.0 km / ~24 min walk, or Metro Ibiza",
      coordSource: "OSM node La Tasca del Retiro /5254388141",
      hours:
        "Mon–Sat 12:00–00:00; Sun 13:00–18:00. Kitchen Mon–Sat 13:00–16:30 & 19:00–23:30; Sun 13:00–16:00 (latascadelretiro.es). Turismo listing is older — prefer the venue site.",
    },
    {
      id: "mercado-paz",
      name: "Mercado de la Paz",
      category: "markets",
      kind: "shopping",
      why: "Salamanca market. Cheese and jamón.",
      neighborhood: "Salamanca",
      address: "Calle de Ayala, 28, 28001 Madrid",
      lat: 40.4271797,
      lng: -3.6857552,
      takeaway:
        "Working Salamanca market since 1882: cheese, jamón, produce. Tables in the middle. Casa Dani is the cheap tapas stall inside — own pin.",
      use: "Working Salamanca market. Cheese and jamón.",
      link: "https://www.esmadrid.com/compras/mercado-de-la-paz",
      linkLabel: "Turismo Madrid",
      extraLinks: [
        { href: "https://www.mercadodelapaz.com/", label: "mercadodelapaz.com" },
      ],
      walk: "~1.7 km / ~21 min walk, or Metro Serrano",
      coordSource: "OSM way Mercado de la Paz /330451579",
      hours: "Mon–Fri 9:00–20:00; Sat 9:00–14:30; Sun closed (Turismo Madrid, Apr 2026). Hours vary by stall.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Madrid%20-%20Mercado%20de%20la%20Paz%2002.jpg?width=400",
        alt: "Mercado de la Paz, Madrid",
        credit: "Zarateman / Wikimedia Commons",
        license: "CC0",
        page: "https://commons.wikimedia.org/wiki/File:Madrid_-_Mercado_de_la_Paz_02.jpg",
      },
    },
    {
      id: "casa-dani",
      name: "Casa Dani",
      category: "food",
      kind: "food",
      why: "Cheap tortilla stall. Go early.",
      neighborhood: "Salamanca",
      address: "Mercado de la Paz, Calle de Ayala, 28, 28001 Madrid",
      lat: 40.4271797,
      lng: -3.6857552,
      takeaway:
        "Old-school cheap tapas stall inside Mercado de la Paz — not a second market. This pin is the market bar, not the Lagasca terrace or other branches. Famous for tortilla.",
      use: "Cheap tapas at the stall. Go early for tortilla.",
      link: "https://en.casadani.es/horario",
      linkLabel: "casadani.es",
      walk: "~1.7 km / ~21 min walk, or Metro Serrano",
      coordSource: "same building as Mercado de la Paz (OSM way/330451579); stall is inside",
      hours: "Market bar Mon–Fri 7:00–20:00; Sat 7:00–17:00; Sun and many holidays closed (casadani.es).",
    },
    {
      id: "azotea-circulo",
      name: "Azotea del Círculo",
      category: "entertainment",
      kind: "sites",
      why: "Rooftop views. Pay the access fee.",
      rating: { score: 4.2, count: 10510, source: "Google", asOf: "2026-08" },
      neighborhood: "Sol / Gran Vía",
      address: "Calle del Marqués de Casa Riera, 2, 28014 Madrid",
      lat: 40.4182071,
      lng: -3.6965142,
      takeaway:
        "Círculo de Bellas Artes rooftop. Views over Gran Vía / Alcalá. Small access fee; ticket does not guarantee a café table.",
      use: "Rooftop views. Pay the access fee.",
      link: "https://www.circulobellasartes.com/en/azotea/",
      linkLabel: "circulobellasartes.com",
      extraLinks: [
        { href: "https://azoteadelcirculo.azoteagrupo.com/home-en/", label: "Azotea site" },
        { href: "https://www.esmadrid.com/en/nightlife/azotea-del-circulo", label: "Turismo Madrid" },
      ],
      walk: "~0.5 km / ~6 min walk",
      tourist: "soft",
      coordSource: "OSM way Círculo de Bellas Artes /4291319",
      hours:
        "Sun–Thu 10:00–1:30, last entry 00:30; Fri–Sat 10:00–2:00, last entry 01:00. Access typically €6 / reduced €5 (Círculo, 2026). Tickets at reception 14:00–16:00 and after 21:00; otherwise online. Check site.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Calle%20de%20Alcal%C3%A1%20(Madrid)%2024.jpg?width=400",
        alt: "View of Calle de Alcalá from the Círculo de Bellas Artes rooftop",
        credit: "Riverac / Wikimedia Commons",
        license: "CC BY 2.0",
        page: "https://commons.wikimedia.org/wiki/File:Calle_de_Alcalá_(Madrid)_24.jpg",
      },
    },
    {
      id: "rosaleda-retiro",
      name: "Bar Mirador La Rosaleda",
      category: "entertainment",
      kind: "landmarks",
      why: "Drink by the rose garden.",
      neighborhood: "Retiro",
      address: "Paseo del Uruguay, 3, 28009 Madrid (inside Parque del Retiro)",
      lat: 40.4117503,
      lng: -3.6799242,
      takeaway:
        "Park kiosk by the Retiro rose garden. A drink with roses, not a destination restaurant. Park and garden hours can shut it.",
      use: "Drink by the rose garden.",
      link: "https://www.esmadrid.com/en/tourist-information/la-rosaleda-de-el-retiro",
      linkLabel: "Turismo Madrid (rose garden)",
      walk: "~2.1 km / ~25 min walk, inside Retiro",
      coordSource: "OSM way Bar Mirador La Rosaleda /467641934",
      hours:
        "Rose garden Apr–Sep 10:00–20:00; Oct–Mar 10:00–18:00 (Turismo). Bar hours unpublished — typically daytime, park-dependent. Check site.",
    },
    {
      id: "san-gines",
      name: "Chocolatería San Ginés",
      category: "food",
      kind: "food",
      why: "The tourist churro line.",
      neighborhood: "Sol",
      address: "Pasadizo de San Ginés, 5, 28013 Madrid",
      lat: 40.4167707,
      lng: -3.706803,
      takeaway:
        "THE tourist churro line since 1894. Late-night classic. 1902 is the less-packed alternative one street over.",
      use: "Late-night classic. 1902 is quieter one street over.",
      link: "https://chocolateriasangines.com/",
      linkLabel: "chocolateriasangines.com",
      extraLinks: [
        { href: "https://www.esmadrid.com/noche/chocolateria-de-san-gines", label: "Turismo Madrid" },
      ],
      walk: "~0.4 km / ~5 min walk",
      tourist: "heavy",
      coordSource: "OSM node Chocolatería San Ginés /178821166",
      hours: "Mon–Wed 8:00–24:00; Thu–Sun and holiday eves 24 hours (Turismo + official contact). Check site.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Chocolater%C3%ADa%20%22San%20Gines%22-Madrid-2009.jpg?width=400",
        alt: "Chocolatería San Ginés",
        credit: "Tamorlan / Wikimedia Commons",
        license: "CC BY 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Chocolatería_\"San_Gines\"-Madrid-2009.jpg",
      },
    },
    {
      id: "el-riojano",
      name: "Confitería El Riojano",
      category: "food",
      kind: "shopping",
      why: "1855 pastry shop. Buy to take.",
      neighborhood: "Sol / Gran Vía",
      address: "Calle Mayor, 10, 28013 Madrid",
      lat: 40.4164965,
      lng: -3.7059265,
      takeaway:
        "1855 pastry shop; historic supplier to the royal household. Tea room at the back. Breakfast or an afternoon pastry near Sol.",
      use: "Breakfast or afternoon pastry.",
      link: "https://www.esmadrid.com/compras/el-riojano",
      linkLabel: "Turismo Madrid",
      extraLinks: [
        { href: "https://pasteleriaelriojano.com/", label: "pasteleriaelriojano.com" },
      ],
      walk: "~0.4 km / ~5 min walk",
      coordSource: "OSM node El Riojano /7161261885",
      hours: "Daily 9:00–21:00. Summer and holiday closures — check pasteleriaelriojano.com (Turismo Madrid, May 2026).",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Pasteler%C3%ADa-El%20Riojano-2009.jpg?width=400",
        alt: "Façade of Pastelería El Riojano",
        credit: "Tamorlan / Wikimedia Commons",
        license: "CC BY 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Pastelería-El_Riojano-2009.jpg",
      },
    },
  ],
  days: [
    {
      id: "day1",
      title: "Day 1",
      subtitle: "Hotel / Sol",
      transit: "Walk from Thompson. Metro Sol or Gran Vía if you want a ride.",
      slots: [
        {
          id: "stay",
          when: "Stay",
          placeId: "thompson",
          text: "Thompson Madrid, Plaza del Carmen. Home base.",
        },
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "mostenses",
          altId: "chocolateria-1902",
          text: "Mercado de los Mostenses. Working market behind Gran Vía. Or 1902 for churros near the hotel.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "gran-via",
          text: "Gran Vía / teatro walk. Short hop from the hotel.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "ardosa",
          altId: "angel-sierra",
          text: "La Ardosa or Ángel Sierra. Ardosa before ~7pm.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "pez-tortilla",
          altId: "casa-julio",
          text: "Pez Tortilla or Casa Julio. Both nearby in Malasaña.",
        },
      ],
    },
    {
      id: "day2",
      title: "Day 2",
      subtitle: "Chamberí",
      transit: "Metro toward Bilbao or Iglesia / Ríos Rosas. Walk between nearby stops.",
      slots: [
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "chamberi-market",
          text: "Mercado de Chamberí in the morning. Jamón stalls on the card.",
        },
        {
          id: "coffee",
          when: "Coffee",
          placeId: "comercial",
          text: "Café Comercial at Bilbao. Historic, a bit touristy.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "taberna-la-mina",
          altId: "chamberi-market",
          text: "Taberna La Mina (likely) or stay at the market.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "anden-0",
          altId: "olavide",
          text: "Andén 0 (book ahead) or a pause at Plaza de Olavide.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "el-doble",
          altId: "ponzano",
          text: "El Doble, then Ponzano if you want a crawl.",
        },
      ],
    },
    {
      id: "day3",
      title: "Day 3",
      subtitle: "Malasaña / Barceló",
      transit: "Walk north from the hotel, or Metro Tribunal / Alonso Martínez.",
      slots: [
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "churreria-madrid-1883",
          text: "Churrería Madrid 1883. Likely — neighborhood match, not a confirmed tour stop.",
        },
        {
          id: "coffee",
          when: "Coffee",
          placeId: "la-comunal",
          text: "La Comunal. Olive-oil shop, not a café. Confirmed Walk and Eat partner.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "barcelo",
          text: "Mercado Barceló. Ask for Daniel, Gemma, Roberto.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "casa-baranda",
          altId: "ardosa",
          text: "Casa Baranda or La Ardosa. Same Colón block.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "conde-duque",
          altId: "historia",
          text: "Conde Duque or the Museo de Historia on Fuencarral.",
        },
      ],
    },
    {
      id: "day4",
      title: "Day 4",
      subtitle: "Sunday / La Latina",
      transit: "Walk south from Thompson, or Metro La Latina (L5).",
      slots: [
        {
          id: "breakfast",
          when: "Breakfast / morning",
          placeId: "el-rastro",
          text: "Sunday flea market. Go early (9–11). Midday is a crush.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "cava-baja",
          altId: "cebada",
          text: "Cava Baja tapas crawl. Mercado de la Cebada if you want a market hall instead (first Sunday of the month / check site).",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "palacio-real",
          altId: "campo-del-moro",
          text: "Palace (book timed entry) or Campo del Moro gardens behind it.",
        },
        {
          id: "dinner",
          when: "Dinner / sunset",
          placeId: "riu-360",
          altId: "cava-baja",
          text: "Riu sky bar / rooftop for sunset, or stay in Latina.",
        },
      ],
    },
  ],
  tours: [
    {
      name: "Culinary Backstreets — The Real Madrid",
      detail: "~$160 / 5h in Chamberí. Visitor writeup names Café Comercial; other stops unpublished.",
      link: "https://culinarybackstreets.com/food-tours/madrid/the-real-madrid-markets-tapas-tradition",
    },
    {
      name: "Flavours of Madrid — Chamberí",
      detail: "€99–119. Includes Chamberí Market concepts. Do not assume unpublished stop names.",
      link: "https://www.flavoursofmadrid.com/authentic-madrid-tapas-tour-madrid",
    },
    {
      name: "Walk and Eat Spain — Malasaña market morning",
      detail: "~$100–140. Mercado Barceló. Explicitly skips San Miguel.",
      link: "https://www.walkandeatspain.com/madrid-neighborhood-market-food-tour",
    },
  ],
};
