/* Madrid guide data.
 * Coordinates: listed where given; otherwise Wikipedia or OSM Nominatim.
 * Do not add places, quotes, or prices that are not in this file.
 * Hours: official / Turismo Madrid / venue sites. Unknown or seasonal → Hours: check site.
 * Photos: Wikimedia Commons only (hotlink + credit). Skip if no Commons file.
 */
window.GUIDE = {
  hotel: {
    lat: 40.41857,
    lng: -3.70267,
  },
  /* Default view: Sol/Gran Vía at the south, Chamberí/Malasaña to the north */
  map: {
    center: [40.4282, -3.7024],
    zoom: 14,
  },
  categories: [
    { id: "stay", label: "Stay" },
    { id: "food", label: "Eat" },
    { id: "markets", label: "Markets" },
    { id: "entertainment", label: "See" },
  ],
  barrios: [
    { id: "all", label: "All" },
    { id: "sol", label: "Sol" },
    { id: "chamberi", label: "Chamberí" },
    { id: "malasana", label: "Malasaña / Chueca" },
    { id: "latina", label: "La Latina" },
    { id: "other", label: "Other" },
  ],
  places: [
    {
      id: "thompson",
      name: "Thompson Madrid",
      category: "stay",
      neighborhood: "Sol / Gran Vía",
      address: "Plaza del Carmen, s/n, 28013 Madrid",
      lat: 40.41857,
      lng: -3.70267,
      takeaway: "Hyatt / Thompson Hotels. Home base — walking notes are from here.",
      link: "https://www.hyatt.com/hotel/spain/thompson-madrid/madrp",
      linkLabel: "Hyatt listing",
      walk: "You are here",
      coordSource: "provided; matches OSM way/265317799",
      hours: "Hours: check site",
    },
    {
      id: "chamberi-market",
      name: "Mercado de Chamberí",
      category: "markets",
      neighborhood: "Chamberí",
      address: "Calle de Alonso Cano, 10, 28010 Madrid",
      lat: 40.43622,
      lng: -3.69762,
      takeaway: "Working market since 1943: produce, meat, fish, plus a gastro area. Weekday mornings best.",
      use: "Weekday mornings.",
      link: "https://mercadodechamberi.es",
      linkLabel: "mercadodechamberi.es",
      walk: "~2.8 km / ~35 min walk, or Metro",
      shops: [
        {
          name: "Jamonera Castellana",
          note: "Since 1964.",
          link: "https://mercadodechamberi.es/jamonera-castellana",
        },
        {
          name: "Jamonería de Juan",
          note: "Since 1981.",
          link: "https://mercadodechamberi.es/jamoneria-de-juan",
        },
        {
          name: "Casa Tere",
          note: "Mon–Sat mornings typical.",
          link: "https://mercadodechamberi.es/casa-tere",
        },
      ],
      coordSource: "Wikipedia 40.43622222, -3.69761944",
      hours: "Stalls Mon–Fri 9:30–14:00 & 17:00–20:00; Sat 9:30–14:30. Kitchen Tue–Sat lunch + dinner; Sun lunch; Mon closed.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercado%20de%20Chamber%C3%AD%20%28Madrid%29%2001.jpg?width=400",
        alt: "Façade of Mercado de Chamberí",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0 ES",
        page: "https://commons.wikimedia.org/wiki/File:Mercado_de_Chamberí_(Madrid)_01.jpg",
      },
    },
    {
      id: "barcelo",
      name: "Mercado Barceló",
      category: "markets",
      neighborhood: "Chueca / Justicia (Malasaña edge)",
      address: "Calle de Barceló, 6, 28004 Madrid",
      lat: 40.42681,
      lng: -3.69928,
      takeaway: "Modern rebuild: traditional floors plus upper-level food. Walk and Eat Spain tours use this market.",
      link: "https://mercadobarcelo.es/",
      linkLabel: "mercadobarcelo.es",
      extraLinks: [
        { href: "https://mercadobarcelo.es/puestos-mercado", label: "Stall directory" },
      ],
      walk: "~1.5 km / ~18 min walk",
      shops: [
        {
          name: "Ask for Daniel",
          note: "3rd-generation produce. Stall trade name unpublished.",
        },
        {
          name: "Ask for Gemma",
          note: "Cheese. Stall trade name unpublished.",
        },
        {
          name: "Ask for Roberto",
          note: "Olives. Likely Aceitunas del Campo, puesto 215 — not a published stall name on the tour page.",
        },
      ],
      unnamed:
        "Ham slicer José and Pedro & Carlos’s family tapas bar are unpublished — no invented shop names here.",
      confidence: "confirmed",
      confidenceNote: "Confirmed Walk and Eat market. Vendor first names published; stall trade names unpublished.",
      coordSource: "provided",
      hours: "Floors 0–1 Mon–Fri 9:00–14:30 & 17:30–20:30; Sat 9:00–15:00. Floor 2 food daily 11:00–01:00. Seasonal — check site.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercado-Barcelo-151217.jpg?width=400",
        alt: "Mercado de Barceló",
        credit: "FDV / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Mercado-Barcelo-151217.jpg",
      },
    },
    {
      id: "aceitunas-del-campo",
      name: "Aceitunas del Campo",
      category: "markets",
      neighborhood: "Mercado Barceló",
      address: "Mercado Barceló, puesto 215, Calle de Barceló, 6, 28004 Madrid",
      lat: 40.42681,
      lng: -3.69928,
      takeaway: "Olive stall inside Barceló. Likely Roberto’s stop on the Walk and Eat market morning.",
      link: "https://mercadobarcelo.es/puestos-mercado",
      linkLabel: "Barceló stall directory",
      walk: "~1.5 km / ~18 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "same building as Mercado Barceló (provided); stall is inside",
      hours: "Hours: check site",
    },
    {
      id: "la-comunal",
      name: "La Comunal",
      category: "food",
      neighborhood: "Chueca / Justicia",
      address: "Calle de Mejía Lequerica, 1, 28004 Madrid",
      lat: 40.42596,
      lng: -3.69735,
      takeaway:
        "Fundación Patrimonio Comunal Olivarero olive-oil shop. Walk and Eat partner (Óleo Revista, Nov 2024). Mon–Fri 10:00–14:00 & 17:00–20:00, Sat 10:00–14:00; often closed August.",
      link: "https://www.esmadrid.com/en/shopping/comunal",
      linkLabel: "Turismo Madrid",
      walk: "~2.1 km / ~25 min walk",
      confidence: "confirmed",
      confidenceNote: "Confirmed Walk and Eat partner.",
      coordSource: "OSM node Patrimonio Comunal Olivarero /2777281755",
      hours: "Mon–Fri 10:00–14:00 & 17:00–20:00; Sat 10:00–14:00. Often closed August — check site.",
    },
    {
      id: "vallehermoso",
      name: "Mercado de Vallehermoso",
      category: "markets",
      neighborhood: "Chamberí",
      address: "Calle de Vallehermoso, 36, 28015 Madrid",
      lat: 40.43413,
      lng: -3.70834,
      takeaway: "Framed as a local alternative to San Miguel: working market plus popular food stalls (Tripea among them).",
      link: "https://www.esmadrid.com/compras/mercado-vallehermoso",
      linkLabel: "Turismo Madrid",
      walk: "~2.4 km / ~30 min walk",
      coordSource: "Wikipedia 40.434125, -3.708336",
      hours: "Hours: check site",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercado%20de%20Vallehermoso%20-%20Madrid.jpg?width=400",
        alt: "Mercado de Vallehermoso",
        credit: "Tamorlan / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Mercado_de_Vallehermoso_-_Madrid.jpg",
      },
    },
    {
      id: "mostenses",
      name: "Mercado de los Mostenses",
      category: "markets",
      neighborhood: "Behind Gran Vía",
      address: "Plaza de los Mostenses, 1, 28015 Madrid",
      lat: 40.42329,
      lng: -3.70906,
      takeaway: "Multicultural working market. CN Traveler called it “anti-posh”; José Andrés has praised the Latin American stalls. Renovated 2024 (Turismo Madrid).",
      link: "https://www.esmadrid.com/compras/mercado-de-los-mostenses",
      linkLabel: "Turismo Madrid",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM relation/4425587",
      hours: "Food Mon–Fri 9:00–14:00 & 17:00–20:00; Sat 9:00–15:00. Hours vary by stall.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercado%20de%20los%20Mostenses%20-%20Madrid%2001.jpg?width=400",
        alt: "Mercado de los Mostenses",
        credit: "Javier Perez Montes / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Mercado_de_los_Mostenses_-_Madrid_01.jpg",
      },
    },
    {
      id: "el-doble",
      name: "El Doble",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle de Ponzano, 58, 28003 Madrid",
      lat: 40.44136,
      lng: -3.69924,
      takeaway: "Standing classic: dobles plus seafood/conservas. Go early. Natural start for a Ponzano evening.",
      use: "Stand at the bar. Go early.",
      link: "https://www.esmadrid.com/restaurantes/el-doble",
      linkLabel: "Turismo Madrid",
      walk: "~2.5 km north / Metro L1 is easier than walking",
      coordSource: "OSM Nominatim for Calle de Ponzano 58",
      hours: "Hours: check site",
    },
    {
      id: "ardosa",
      name: "Bodega de La Ardosa",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle de Colón, 13, 28004 Madrid",
      lat: 40.42377,
      lng: -3.70177,
      takeaway: "Vermú and tortilla. CN Traveler: in all the guides, so tourist influx. Arrive before ~7pm.",
      use: "Stand at the bar. Before ~7pm.",
      link: "https://www.esmadrid.com/en/restaurants/bodega-ardosa",
      linkLabel: "Turismo Madrid",
      walk: "~0.8 km / ~10 min walk",
      tourist: "heavy",
      coordSource: "OSM node Bodega de la Ardosa /2585147466",
      hours: "Sun–Thu 9:00–2:00; Fri–Sat 9:00–2:30",
    },
    {
      id: "casa-baranda",
      name: "Casa Baranda",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle de Colón, 11, 28004 Madrid",
      lat: 40.42376,
      lng: -3.70165,
      takeaway: "Ardosa group, next door. Same block, same timing advice.",
      use: "Go early — same block as Ardosa.",
      walk: "~0.8 km / ~10 min walk",
      coordSource: "OSM node Casa Baranda /2661123393",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Casa%20Baranda%20Calle%20de%20Col%C3%B3n%2011%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "casa-julio",
      name: "Casa Julio",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle de la Madera, 37, 28004 Madrid",
      lat: 40.42431,
      lng: -3.70366,
      takeaway: "Croquetas since 1921.",
      link: "https://www.esmadrid.com/restaurantes/casa-julio",
      linkLabel: "Turismo Madrid",
      walk: "~1 km / ~12 min walk",
      coordSource: "OSM node Casa Julio /2583954354",
      hours: "Hours: check site",
    },
    {
      id: "pez-tortilla",
      name: "Pez Tortilla",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle del Pez, 36, 28004 Madrid",
      lat: 40.42425,
      lng: -3.70649,
      takeaway: "Tortillas, croquetas, craft beer. No reservations. This pin is the Malasaña original, not other branches.",
      use: "No reservations.",
      link: "https://peztortilla.com/",
      linkLabel: "peztortilla.com",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM node Pez Tortilla /2630111357",
      hours: "Hours: check site",
    },
    {
      id: "churreria-madrid-1883",
      name: "Churrería Madrid 1883",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle del Espíritu Santo, 8, 28004 Madrid",
      lat: 40.42514,
      lng: -3.70258,
      takeaway:
        "Malasaña classic for churros and chocolate. Neighborhood vibe match; not proven as Walk and Eat’s first stop.",
      walk: "~1.3 km / ~16 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM node Madrid 1883 Churreria /6325195806",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Churrer%C3%ADa%20Madrid%201883%20Esp%C3%ADritu%20Santo",
      linkLabel: "Google Maps",
    },
    {
      id: "angel-sierra",
      name: "Taberna Ángel Sierra",
      category: "food",
      neighborhood: "Plaza Chueca",
      address: "Calle de Gravina, 11, 28004 Madrid",
      lat: 40.42302,
      lng: -3.69746,
      takeaway: "Historic vermouth taberna. Early is easier than peak evening.",
      use: "Go early.",
      link: "https://tabernadeangelsierra.es/",
      linkLabel: "tabernadeangelsierra.es",
      walk: "~1.9 km / ~25 min walk",
      coordSource: "OSM node Taberna de Ángel Sierra /3897299367",
      hours: "Hours: check site",
    },
    {
      id: "casa-hortensia",
      name: "Casa Hortensia",
      category: "food",
      neighborhood: "Chueca / Justicia",
      address: "Calle de la Farmacia, 2, 28004 Madrid",
      lat: 40.42387,
      lng: -3.70043,
      takeaway: "Asturian fabada.",
      link: "https://www.esmadrid.com/restaurantes/casa-hortensia",
      linkLabel: "Turismo Madrid",
      walk: "~1 km / ~12 min walk",
      coordSource: "OSM node Casa Hortensia /2661121483",
      hours: "Hours: check site",
    },
    {
      id: "caja-de-cerillas",
      name: "Caja de Cerillas",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle de Donoso Cortés, 8, 28015 Madrid",
      lat: 40.43617,
      lng: -3.70547,
      takeaway: "Newer (2025) neo-castizo. Thinner reputation than the old names — book if you go.",
      walk: "~2.4 km / ~30 min walk",
      coordSource: "OSM node Caja De Cerillas /12880638622",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Caja%20de%20Cerillas%20Donoso%20Cort%C3%A9s%208%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "sala-de-despiece",
      name: "Sala de Despiece (SDD1)",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle de Alonso Cano, 27–28, 28010 Madrid",
      lat: 40.43757,
      lng: -3.69805,
      takeaway:
        "Theatrical counter. Moved here from Ponzano 11. Likely Culinary Backstreets finale per a visitor writeup.",
      walk: "~3.0 km / ~36 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM building Calle de Alonso Cano 27 way/385080174 (OSM still lists the old Ponzano 11 restaurant node; pin uses the stated new address)",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Sala%20de%20Despiece%20Alonso%20Cano%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "taberna-la-mina",
      name: "Taberna La Mina",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle del General Álvarez de Castro, 8, 28010 Madrid",
      lat: 40.43483,
      lng: -3.70174,
      takeaway: "Founded 1949. Possible Flavours “since 1949” stop — not a slam dunk.",
      walk: "~2.6 km / ~31 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM node Taberna La Mina /2651989201",
      hours: "Hours: check site",
      link: "https://www.google.com/maps/search/?api=1&query=Taberna%20La%20Mina%20General%20%C3%81lvarez%20de%20Castro%208%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "comercial",
      name: "Café Comercial",
      category: "food",
      neighborhood: "Glorieta de Bilbao",
      address: "Glorieta de Bilbao, 7, 28004 Madrid",
      lat: 40.42871,
      lng: -3.70197,
      takeaway: "Historic café. Culinary Backstreets’ Chamberí tour starts here. Mixed “touristy post-reopen” comments.",
      link: "https://www.wheregoesrose.com/madrid-food-tour-culinary-backstreets/",
      linkLabel: "Visitor writeup (wheregoesrose.com)",
      walk: "~2.0 km / ~25 min walk",
      tourist: "soft",
      extraLinks: [
        { href: "https://cafecomercialmadrid.com/", label: "cafecomercialmadrid.com" },
      ],
      coordSource: "OSM node Café Comercial /26065697",
      hours: "Hours: check site",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Caf%C3%A9%20Comercial%20%28Madrid%29%2002.jpg?width=400",
        alt: "Café Comercial",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Café_Comercial_(Madrid)_02.jpg",
      },
    },
    {
      id: "ponzano",
      name: "Calle Ponzano crawl",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle de Ponzano, Chamberí",
      lat: 40.43767,
      lng: -3.69941,
      takeaway: "“Ponzaning”: a corridor of ~70 bars. Crowded Thu–Sat. Start at El Doble if you only do one.",
      use: "Crowded Thu–Sat.",
      walk: "North of Bilbao; Metro L1 toward Ríos Rosas",
      tourist: "soft-weekends",
      coordSource: "OSM way Calle de Ponzano (Almagro stretch) /8029884",
      hours: "Hours: varies by bar",
      link: "https://www.google.com/maps/search/?api=1&query=Calle%20de%20Ponzano%20Chamber%C3%AD%20Madrid",
      linkLabel: "Google Maps",
    },
    {
      id: "anden-0",
      name: "Andén 0 – Estación de Chamberí",
      category: "entertainment",
      neighborhood: "Chamberí",
      address: "Plaza de Chamberí, s/n, 28010 Madrid",
      lat: 40.4323,
      lng: -3.69772,
      takeaway: "Ghost metro museum. Free; book ahead.",
      use: "Book ahead.",
      link: "https://museosmetromadrid.es/estacion-de-chamberi_0/",
      linkLabel: "Museos Metro Madrid",
      walk: "~2.5 km / ~30 min walk",
      coordSource: "Wikipedia 40.4323, -3.69772",
      hours: "Fri 16:00–20:00; Sat 10:00–14:00 & 16:00–20:00; Sun 10:00–14:00. Book ahead. Closed Christmas, New Year, Reyes.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/And%C3%A9n%200%20Estaci%C3%B3n%20de%20Chamber%C3%AD%20en%20septiembre%20de%202022%2001.jpg?width=400",
        alt: "Andén 0, Estación de Chamberí",
        credit: "Emilio J. Rodríguez Posada / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Andén_0_Estación_de_Chamberí_en_septiembre_de_2022_01.jpg",
      },
    },
    {
      id: "beti-jai",
      name: "Frontón Beti Jai",
      category: "entertainment",
      neighborhood: "Chamberí / Almagro",
      address: "Calle del Marqués del Riscal, 7, 28010 Madrid",
      lat: 40.43067,
      lng: -3.69116,
      takeaway: "1894 pelota court. National Monument.",
      walk: "~2.3 km / ~28 min walk",
      coordSource: "provided; OSM way/965335844 nearby",
      hours: "Tue–Sun; summer (15 Jun–30 Sep) 10:00–18:00; rest of year 10:00–14:00. Free. Check site.",
      link: "https://www.esmadrid.com/informacion-turistica/fronton-beti-jai",
      linkLabel: "Turismo Madrid",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Front%C3%B3n%20Beti%20Jai%20de%20Madrid%20en%20octubre%20de%202023%2001.jpg?width=400",
        alt: "Frontón Beti Jai",
        credit: "Emilio J. Rodríguez Posada / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Frontón_Beti_Jai_de_Madrid_en_octubre_de_2023_01.jpg",
      },
    },
    {
      id: "sorolla",
      name: "Museo Sorolla",
      category: "entertainment",
      neighborhood: "Chamberí / Almagro",
      address: "Paseo del General Martínez Campos, 37, 28010 Madrid",
      lat: 40.4354,
      lng: -3.69254,
      takeaway: "Temporarily closed since October 2024 for expansion. Do not plan a visit.",
      link: "https://www.madrid.es/portales/munimadrid/es/Inicio/Cultura-ocio-y-deporte/Cultura-y-ocio/Direcciones-y-telefonos/Museo-Sorolla/",
      linkLabel: "Ayuntamiento de Madrid",
      closed: true,
      coordSource: "Wikipedia 40.435404, -3.692539",
      hours: "Closed (expansion). Check site for reopening.",
    },
    {
      id: "geominero",
      name: "Museo Geominero",
      category: "entertainment",
      neighborhood: "Chamberí",
      address: "Calle de Ríos Rosas, 23, 28003 Madrid",
      lat: 40.4427,
      lng: -3.6996,
      takeaway: "Free geology museum. Open mornings.",
      link: "https://www.igme.es/museo/visitanos/",
      linkLabel: "IGME – Visítanos",
      walk: "Near El Doble / Ríos Rosas Metro",
      coordSource: "Wikipedia 40.4427, -3.6996",
      hours: "Daily 9:00–14:00, including holidays. Closed 24–25 & 31 Dec, 1 & 6 Jan. Free.",
    },
    {
      id: "olavide",
      name: "Plaza de Olavide",
      category: "entertainment",
      neighborhood: "Chamberí",
      address: "Plaza de Olavide, 28010 Madrid",
      lat: 40.43305,
      lng: -3.7006,
      takeaway: "Local octagonal plaza with terraces. A pause, not a monument.",
      walk: "~2.2 km / ~27 min walk",
      coordSource: "OSM way Plaza de Olavide /248905968",
      hours: "Open plaza",
      link: "https://www.google.com/maps/search/?api=1&query=Plaza%20de%20Olavide%20Madrid",
      linkLabel: "Google Maps",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20la%20Plaza%20de%20Olavide%20de%20Madrid.jpg?width=400",
        alt: "Plaza de Olavide",
        credit: "Jotaemec / Wikimedia Commons",
        license: "CC0",
        page: "https://commons.wikimedia.org/wiki/File:Vista_de_la_Plaza_de_Olavide_de_Madrid.jpg",
      },
    },
    {
      id: "canal",
      name: "Teatros del Canal",
      category: "entertainment",
      neighborhood: "Chamberí",
      address: "Calle de Cea Bermúdez, 1, 28003 Madrid",
      lat: 40.43844,
      lng: -3.70506,
      takeaway: "Performing arts. Check the calendar if you want a show.",
      link: "https://www.teatroscanal.com/",
      linkLabel: "teatroscanal.com",
      walk: "~2.7 km / ~35 min walk",
      coordSource: "Wikipedia 40.438441, -3.705059",
      hours: "Hours: check site",
    },
    {
      id: "conde-duque",
      name: "Centro Cultural Conde Duque",
      category: "entertainment",
      neighborhood: "Malasaña / Conde Duque",
      address: "Calle del Conde Duque, 9–11, 28015 Madrid",
      lat: 40.42785,
      lng: -3.71068,
      takeaway: "Municipal cultural centre in the old barracks. Exhibitions, concerts, courtyard.",
      walk: "~1.8 km / ~22 min walk",
      coordSource: "Wikipedia 40.427852, -3.710681",
      hours: "Hours: check site",
      link: "https://www.condeduquemadrid.es/",
      linkLabel: "condeduquemadrid.es",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuartel%20del%20Conde-Duque%20%28Madrid%29%2005.jpg?width=400",
        alt: "Conde Duque",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Cuartel_del_Conde-Duque_(Madrid)_05.jpg",
      },
    },
    {
      id: "historia",
      name: "Museo de Historia de Madrid",
      category: "entertainment",
      neighborhood: "Malasaña",
      address: "Calle de Fuencarral, 78, 28004 Madrid",
      lat: 40.42579,
      lng: -3.70076,
      takeaway: "City history museum on Fuencarral. Useful rainy-hour stop.",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM node Museo de Historia de Madrid /12921081474",
      hours: "Tue–Sun 10:00–20:00; summer (15 Jun–15 Sep) 10:00–19:00. Closed Mon and 1 & 6 Jan, 1 May, 24–25 & 31 Dec. Free.",
      link: "https://www.esmadrid.com/informacion-turistica/museo-de-historia",
      linkLabel: "Turismo Madrid",
    },
    {
      id: "escultura",
      name: "Museo de Escultura al Aire Libre",
      category: "entertainment",
      neighborhood: "Castellana / Rubén Darío",
      address: "Paseo de la Castellana, 40, 28046 Madrid",
      lat: 40.43303,
      lng: -3.68748,
      takeaway: "Free outdoor sculpture under the Juan Bravo overpass, near Rubén Darío.",
      link: "https://www.esmadrid.com/informacion-turistica/museo-escultura-aire-libre-castellana",
      linkLabel: "Turismo Madrid",
      walk: "~2.5 km / ~30 min walk",
      coordSource: "Wikipedia 40.43303, -3.68748",
      hours: "Open-air — always open",
    },
    {
      id: "gran-via",
      name: "Gran Vía / Teatro district walk",
      category: "entertainment",
      neighborhood: "Sol / Gran Vía",
      address: "Plaza de Callao / Gran Vía",
      lat: 40.41986,
      lng: -3.70581,
      takeaway: "Theatre stretch of Gran Vía. Short walk from Thompson — evening lights, not a hidden corner.",
      walk: "~0.5 km / a few minutes",
      coordSource: "OSM Plaza de Callao relation/13452454",
      hours: "Street — always open",
      link: "https://www.esmadrid.com/informacion-turistica/gran-via",
      linkLabel: "Turismo Madrid",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Gran%20V%C3%ADa%20%28Madrid%29%2039.jpg?width=400",
        alt: "Gran Vía, Madrid",
        credit: "ianaiare / Wikimedia Commons",
        license: "CC BY-SA 2.0",
        page: "https://commons.wikimedia.org/wiki/File:Gran_Vía_(Madrid)_39.jpg",
      },
    },
    {
      id: "cava-baja",
      name: "Cava Baja / La Latina",
      category: "food",
      neighborhood: "La Latina",
      address: "Calle de la Cava Baja, 28005 Madrid",
      lat: 40.41236,
      lng: -3.70925,
      takeaway:
        "The tapas street — a crawl, not one restaurant. Popular, still the local evening strip. Not Mercado San Miguel.",
      use: "Evening tapas crawl. Sunday lunch after El Rastro.",
      link: "https://www.esmadrid.com/en/madrid-neighbourhoods/latina",
      linkLabel: "Turismo Madrid",
      walk: "~1.2 km / ~16 min walk",
      tourist: "soft-weekends",
      coordSource: "OSM way Calle de la Cava Baja /4519457",
      hours: "Hours: varies by bar",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Fiestas%20de%20la%20Paloma%202023%20-%20Calle%20de%20la%20Cava%20Baja%20-%20Madrid%2007.jpg?width=400",
        alt: "Calle de la Cava Baja, La Latina",
        credit: "Javier Pérez Montes / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Fiestas_de_la_Paloma_2023_-_Calle_de_la_Cava_Baja_-_Madrid_07.jpg",
      },
    },
    {
      id: "riu-360",
      name: "360° Sky Bar – Hotel Riu Plaza España",
      category: "entertainment",
      neighborhood: "Sol / Gran Vía",
      address: "Gran Vía 84 / Calle del Maestro Guerrero, s/n, 28013 Madrid",
      lat: 40.4242,
      lng: -3.71103,
      takeaway:
        "Tourist sunset rooftop in Edificio España. One ticket covers floor-26 Sky Bar (indoor), floor-27 terrace, and El Edén. Drinks and food. Non-guests pay; hotel guests usually free.",
      use: "Sunset. Book/ticket ahead if required.",
      link: "https://www.riu360rooftopbar.com/en/",
      linkLabel: "riu360rooftopbar.com",
      extraLinks: [
        { href: "https://www.riu.com/blog/en/riu-plaza-espana-terrace-faq/", label: "RIU terrace FAQ" },
      ],
      walk: "~1.3 km / ~16 min walk",
      tourist: "heavy",
      coordSource: "OSM way Hotel Riu Plaza España /1432522463",
      hours:
        "Sky Bar daily 12:00–3:00, kitchen 12:00–00:30. Rooftop daily 11:00–2:00, kitchen 12:00–23:30, last entry midnight. Non-guests: Mon–Fri €5 before 17:00, €10 after; Sat/Sun/holidays €10. Guests usually free.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Madrid%20-%20Hotel%20Riu%20Plaza%20Espa%C3%B1a%204.jpg?width=400",
        alt: "Hotel Riu Plaza España, Edificio España",
        credit: "Zarateman / Wikimedia Commons",
        license: "CC0",
        page: "https://commons.wikimedia.org/wiki/File:Madrid_-_Hotel_Riu_Plaza_España_4.jpg",
      },
    },
    {
      id: "palacio-real",
      name: "Palacio Real",
      category: "entertainment",
      neighborhood: "Austrias",
      address: "Calle de Bailén, s/n, 28013 Madrid",
      lat: 40.41674,
      lng: -3.71362,
      takeaway:
        "The big royal-palace circuit. Timed tickets sell out. Access currently via the Bailén / Requena arch (renovation — Turismo Madrid, Aug 2026).",
      use: "Book timed entry. Pair with Cava Baja / La Latina after if walking south.",
      link: "https://tickets.patrimonionacional.es/en/tickets/palacio-real-de-madrid",
      linkLabel: "Patrimonio Nacional tickets",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/tourist-information/royal-palace", label: "Turismo Madrid" },
      ],
      walk: "~1.3 km / ~17 min walk",
      tourist: "heavy",
      coordSource: "OSM node Palacio Real de Madrid /4451986389",
      hours:
        "Winter (Oct–Mar) Mon–Sat 10:00–18:00, Sun 10:00–16:00. Summer (Apr–Sep) Mon–Sat 10:00–19:00, Sun 10:00–16:00. Last entry 1 hour before close. Closed 1 & 6 Jan, 1 May, 25 Dec; early close 24 & 31 Dec. Official events can shut it.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Palacio%20Real%20%28Madrid%29%2001.jpg?width=400",
        alt: "Palacio Real de Madrid",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Palacio_Real_(Madrid)_01.jpg",
      },
    },
    {
      id: "retiro",
      name: "Parque del Retiro",
      category: "entertainment",
      neighborhood: "Retiro",
      address: "Plaza de la Independencia, 7, 28001 Madrid",
      lat: 40.41981,
      lng: -3.68827,
      takeaway:
        "Pin is the Plaza de la Independencia / Puerta de Alcalá gate (Retiro metro). Free park. Walk the lake. Palacio de Cristal is closed for works; Palacio de Velázquez reopened 24 Jun 2026 — check the museum calendar.",
      use: "Walk, lake, Palacio de Velázquez if open. Palacio de Cristal closed for restoration.",
      link: "https://www.esmadrid.com/informacion-turistica/parque-del-retiro",
      linkLabel: "Turismo Madrid",
      extraLinks: [
        { href: "https://www.museoreinasofia.es/en/visit/opening-times/", label: "Reina Sofía (Retiro palaces)" },
      ],
      walk: "~1.6 km / ~22 min walk",
      tourist: "soft",
      coordSource: "OSM Plaza de la Independencia (Jerónimos) way/43405580; Ayuntamiento address Plaza Independencia 7",
      hours: "Apr–Sep 6:00–00:00; Oct–Mar 6:00–22:00. Free. Weather alerts can close gates.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Estanque%20del%20Retiro%2C%20Parque%20del%20Retiro%2C%20Madrid%2C%20Espa%C3%B1a%2C%202017-05-18%2C%20DD%2016.jpg?width=400",
        alt: "Estanque Grande, Parque del Retiro",
        credit: "Diego Delso / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Estanque_del_Retiro,_Parque_del_Retiro,_Madrid,_España,_2017-05-18,_DD_16.jpg",
      },
    },
    {
      id: "reina-sofia",
      name: "Museo Reina Sofía",
      category: "entertainment",
      neighborhood: "Paseo del Arte",
      address: "Calle de Santa Isabel, 52, 28012 Madrid",
      lat: 40.40805,
      lng: -3.69442,
      takeaway:
        "Guernica is the reason. Prado is next door if you have a second museum day — not required. Free evening window is a crush.",
      use: "Closed Tuesday. Guernica is the target. Free evening window is packed.",
      link: "https://www.museoreinasofia.es/en/visit/opening-times/",
      linkLabel: "museoreinasofia.es",
      walk: "~1.8 km / ~25 min walk, or Metro",
      tourist: "heavy",
      coordSource: "OSM way Museo Nacional Centro de Arte Reina Sofía /991444051",
      hours:
        "Mon + Wed–Sat 10:00–21:00; Sun 10:00–14:30; closed Tue. Free last two hours (Mon/Wed–Sat 19:00–21:00; Sun 12:30–14:30) — still need a ticket. Last entry 30 min before close. General €12.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/MNCARS%2001.jpg?width=400",
        alt: "Museo Reina Sofía",
        credit: "Juan Lupión / Wikimedia Commons",
        license: "CC BY 2.0",
        page: "https://commons.wikimedia.org/wiki/File:MNCARS_01.jpg",
      },
    },
    {
      id: "el-rastro",
      name: "El Rastro",
      category: "markets",
      neighborhood: "La Latina",
      address: "Plaza de Cascorro / Calle de Ribera de Curtidores, 28012 Madrid",
      lat: 40.41058,
      lng: -3.70732,
      takeaway:
        "Sunday flea market from Cascorro down Ribera de Curtidores. Midday is a crush. Pin is Plaza de Cascorro.",
      use: "Sunday morning. Go early. Pair with Cava Baja lunch.",
      link: "https://www.esmadrid.com/en/shopping/el-rastro",
      linkLabel: "Turismo Madrid",
      walk: "~1.3 km / ~17 min walk",
      tourist: "heavy",
      coordSource: "OSM way Plaza de Cascorro /335204867",
      hours: "Sun and public holidays 9:00–15:00. First Saturday of the month (except Jul, Aug, Nov) has a separate antiques fair — check site.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Rastro%20-%20Plaza%20de%20Cascorro%20-%20Madrid%2002.jpg?width=400",
        alt: "El Rastro at Plaza de Cascorro",
        credit: "Javier Perez Montes / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Rastro_-_Plaza_de_Cascorro_-_Madrid_02.jpg",
      },
    },
    {
      id: "la-duquesita",
      name: "La Duquesita",
      category: "food",
      neighborhood: "Salesas / Chueca",
      address: "Calle de Fernando VI, 2, 28004 Madrid",
      lat: 40.4256807,
      lng: -3.6969664,
      takeaway:
        "1914 pastry shop, now Oriol Balaguer. Croissants and Tarta Duquesita get mentioned on Turismo Madrid. Well known — not a hidden bakery.",
      use: "Pastry / tea room. Good any day; not on the Sunday Rastro walk (wrong direction).",
      link: "https://laduquesita.es/",
      linkLabel: "laduquesita.es",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/shopping/la-duquesita", label: "Turismo Madrid" },
      ],
      walk: "~1.2 km / ~15 min walk, Metro Alonso Martínez",
      tourist: "soft",
      coordSource: "OSM node Pastelería La Duquesita /4763918423",
      hours: "Daily 9:00–20:30 (Turismo Madrid, Apr 2026). Check laduquesita.es.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/La%20Duquesita-%20Exterior%20(323354129).jpg?width=400",
        alt: "Exterior of La Duquesita",
        credit: "deramaenrama / Wikimedia Commons",
        license: "CC BY 2.0",
        page: "https://commons.wikimedia.org/wiki/File:La_Duquesita-_Exterior_(323354129).jpg",
      },
    },
    {
      id: "cebada",
      name: "Mercado de la Cebada",
      category: "markets",
      neighborhood: "La Latina",
      address: "Plaza de la Cebada, s/n, 28005 Madrid",
      lat: 40.4110938,
      lng: -3.7098246,
      takeaway:
        "La Latina market hall. Regular Sunday is not a given — only the first Sunday plus posted open Sundays/holidays. MadriZebada outdoor market is first Sunday except August (check the agenda).",
      use: "La Latina market hall. Pair with El Rastro only if it’s a first Sunday or an advertised open Sunday.",
      link: "https://www.mercadodelacebada.com/",
      linkLabel: "mercadodelacebada.com",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/shopping/cebada-market", label: "Turismo Madrid" },
        { href: "https://www.mercadodelacebada.com/mercado/", label: "2026 hours" },
      ],
      walk: "~1.3 km / ~17 min walk, or Metro La Latina (L5)",
      coordSource: "OSM way Mercado de la Cebada /4346296",
      hours:
        "Stalls Mon–Fri 9:00–14:00 & 17:30–20:30; Sat 9:00–18:00. First Sunday 11:00–17:00. Other open Sundays/holidays 11:00–17:00 — not every Sunday; check the 2026 list. MadriZebada (first Sun except Aug) ~12:00–17:00. Hours vary by stall.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Madrid%20-%20Mercado%20de%20la%20Cebada%20-%20outside.jpg?width=400",
        alt: "Outside Mercado de la Cebada",
        credit: "Tiia Monto / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Madrid_-_Mercado_de_la_Cebada_-_outside.jpg",
      },
    },
    {
      id: "campo-del-moro",
      name: "Campo del Moro",
      category: "entertainment",
      neighborhood: "Austrias / palace",
      address: "Paseo de la Virgen del Puerto, s/n, 28005 Madrid",
      lat: 40.4180757,
      lng: -3.717772,
      takeaway:
        "Free gardens directly behind the Royal Palace. Fewer people than the palace rooms. Weather and official events can close it.",
      use: "Free gardens after or instead of the palace tour.",
      link: "https://www.esmadrid.com/informacion-turistica/campo-del-moro",
      linkLabel: "Turismo Madrid",
      extraLinks: [
        { href: "https://www.patrimonionacional.es/visita/jardines-del-campo-del-moro", label: "Patrimonio Nacional" },
      ],
      walk: "~1.7 km / ~21 min walk. Gates: Virgen del Puerto, Cuesta de San Vicente, Cuesta de la Vega.",
      tourist: "soft",
      coordSource: "OSM relation Campo del Moro /1505193",
      hours:
        "Free. Closed 1 Jan, 1 May, 25 Dec; official events / weather can shut it. Virgen del Puerto: Oct–Mar 10:00–18:00; Apr & Sep 10:00–21:00; May–Aug 10:00–22:00. Cuesta de San Vicente: Apr–Sep 10:00–20:00; Oct–Mar 10:00–18:00. Cuesta de la Vega: daily 10:00–20:00. Turismo Madrid, Jan 2026 — check before you go.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Campo%20del%20Moro%20(Madrid)%2004.jpg?width=400",
        alt: "Campo del Moro gardens with the Royal Palace",
        credit: "Bjaglin / Wikimedia Commons",
        license: "CC BY 2.0",
        page: "https://commons.wikimedia.org/wiki/File:Campo_del_Moro_(Madrid)_04.jpg",
      },
    },
    {
      id: "thyssen",
      name: "Museo Thyssen-Bornemisza",
      category: "entertainment",
      neighborhood: "Paseo del Arte",
      address: "Paseo del Prado, 8, 28014 Madrid",
      lat: 40.4162159,
      lng: -3.6949317,
      takeaway:
        "Paseo del Prado art museum. Usually lighter than the Prado rooms. Permanent collection plus temps. Monday afternoon is the free window.",
      use: "Art museum. Fewer crowds than Prado. Pair with Retiro / Reina Sofía if doing the museum mile.",
      link: "https://www.museothyssen.org/en/visit/opening-hours-prices",
      linkLabel: "museothyssen.org",
      extraLinks: [
        { href: "https://www.museothyssen.org/en", label: "Tickets / home" },
      ],
      walk: "~0.9 km / ~12 min walk",
      tourist: "soft",
      coordSource: "OSM relation Museo Thyssen-Bornemisza /1869336",
      hours:
        "Mon 12:00–16:00 (free collection; no ticket). Tue–Fri + Sun 10:00–19:00 (1 Jul–31 Aug Tue–Fri to 21:00). Sat 10:00–23:00 (temps free 21:00–23:00). Last entry 30 min before close. Closed 1 Jan, 1 May, 25 Dec; 24 & 31 Dec 10:00–15:00. General €14. Check site.",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Museo%20Thyssen-Bornemisza%20(Madrid)%2006a.jpg?width=400",
        alt: "Museo Thyssen-Bornemisza, Palacio de Villahermosa",
        credit: "Luis García / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        page: "https://commons.wikimedia.org/wiki/File:Museo_Thyssen-Bornemisza_(Madrid)_06a.jpg",
      },
    },
    {
      id: "botanico",
      name: "Real Jardín Botánico",
      category: "entertainment",
      neighborhood: "Paseo del Arte",
      address: "Plaza de Murillo, 2, 28014 Madrid",
      lat: 40.4114871,
      lng: -3.6906894,
      takeaway:
        "Ticketed CSIC garden next to Prado / Retiro. Tuesday morning has a free window — official and Turismo cutoffs disagree, so check rjb.csic.es.",
      use: "Paid garden next to Prado. Good after Retiro.",
      link: "https://rjb.csic.es/el-jardin/guia-practica/",
      linkLabel: "rjb.csic.es",
      extraLinks: [
        { href: "https://www.esmadrid.com/en/tourist-information/royal-botanic-gardens", label: "Turismo Madrid" },
        { href: "https://entradas.rjb.csic.es", label: "Tickets" },
      ],
      walk: "~1.7 km / ~21 min walk",
      tourist: "soft",
      coordSource: "OSM way Royal Botanical Garden of Madrid /15244804",
      hours:
        "Daily from 10:00. Close Nov–Feb 18:00; Mar & Oct 19:00; Apr & Sep 20:00; May–Aug 21:00. Last entry 30 min before. Closed 1 Jan and 25 Dec. Tue morning free — check site (listings disagree on the cutoff). Gardens €4 (Turismo Madrid, Mar 2026).",
      photo: {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Real%20Jard%C3%ADn%20Bot%C3%A1nico%2C%20Madrid%2C%20Espa%C3%B1a%2C%202017-05-18%2C%20DD%2038.jpg?width=400",
        alt: "Real Jardín Botánico, Madrid",
        credit: "Diego Delso / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        page: "https://commons.wikimedia.org/wiki/File:Real_Jardín_Botánico,_Madrid,_España,_2017-05-18,_DD_38.jpg",
      },
    },
  ],
  days: [
    {
      id: "day1",
      title: "Day 1",
      subtitle: "Hotel / Sol",
      transit: "Walk from Thompson. Metro Sol or Gran Vía if you want a ride.",
      slots: [
        {
          id: "stay",
          when: "Stay",
          placeId: "thompson",
          text: "Thompson Madrid, Plaza del Carmen. Home base.",
        },
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "mostenses",
          text: "Mercado de los Mostenses. Working market behind Gran Vía.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "gran-via",
          text: "Gran Vía / teatro walk. Short hop from the hotel.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "ardosa",
          altId: "angel-sierra",
          text: "La Ardosa or Ángel Sierra. Ardosa before ~7pm.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "pez-tortilla",
          altId: "casa-julio",
          text: "Pez Tortilla or Casa Julio. Both nearby in Malasaña.",
        },
      ],
    },
    {
      id: "day2",
      title: "Day 2",
      subtitle: "Chamberí",
      transit: "Metro toward Bilbao or Iglesia / Ríos Rosas. Walk between nearby stops.",
      slots: [
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "chamberi-market",
          text: "Mercado de Chamberí in the morning. Jamón stalls on the card.",
        },
        {
          id: "coffee",
          when: "Coffee",
          placeId: "comercial",
          text: "Café Comercial at Bilbao. Historic, a bit touristy.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "taberna-la-mina",
          altId: "chamberi-market",
          text: "Taberna La Mina (likely) or stay at the market.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "anden-0",
          altId: "olavide",
          text: "Andén 0 (book ahead) or a pause at Plaza de Olavide.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "el-doble",
          altId: "ponzano",
          text: "El Doble, then Ponzano if you want a crawl.",
        },
      ],
    },
    {
      id: "day3",
      title: "Day 3",
      subtitle: "Malasaña / Barceló",
      transit: "Walk north from the hotel, or Metro Tribunal / Alonso Martínez.",
      slots: [
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "churreria-madrid-1883",
          text: "Churrería Madrid 1883. Likely — neighborhood match, not a confirmed tour stop.",
        },
        {
          id: "coffee",
          when: "Coffee",
          placeId: "la-comunal",
          text: "La Comunal. Olive-oil shop, not a café. Confirmed Walk and Eat partner.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "barcelo",
          text: "Mercado Barceló. Ask for Daniel, Gemma, Roberto.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "casa-baranda",
          altId: "ardosa",
          text: "Casa Baranda or La Ardosa. Same Colón block.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "conde-duque",
          altId: "historia",
          text: "Conde Duque or the Museo de Historia on Fuencarral.",
        },
      ],
    },
    {
      id: "day4",
      title: "Day 4",
      subtitle: "Sunday / La Latina",
      transit: "Walk south from Thompson, or Metro La Latina (L5).",
      slots: [
        {
          id: "breakfast",
          when: "Breakfast / morning",
          placeId: "el-rastro",
          text: "Sunday flea market. Go early (9–11). Midday is a crush.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "cava-baja",
          altId: "cebada",
          text: "Cava Baja tapas crawl. Mercado de la Cebada if you want a market hall instead (first Sunday of the month / check site).",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "palacio-real",
          altId: "campo-del-moro",
          text: "Palace (book timed entry) or Campo del Moro gardens behind it.",
        },
        {
          id: "dinner",
          when: "Dinner / sunset",
          placeId: "riu-360",
          altId: "cava-baja",
          text: "Riu sky bar / rooftop for sunset, or stay in Latina.",
        },
      ],
    },
  ],
  tours: [
    {
      name: "Culinary Backstreets — The Real Madrid",
      detail: "~$160 / 5h in Chamberí. Visitor writeup names Café Comercial; other stops unpublished.",
      link: "https://culinarybackstreets.com/food-tours/madrid/the-real-madrid-markets-tapas-tradition",
    },
    {
      name: "Flavours of Madrid — Chamberí",
      detail: "€99–119. Includes Chamberí Market concepts. Do not assume unpublished stop names.",
      link: "https://www.flavoursofmadrid.com/authentic-madrid-tapas-tour-madrid",
    },
    {
      name: "Walk and Eat Spain — Malasaña market morning",
      detail: "~$100–140. Mercado Barceló. Explicitly skips San Miguel.",
      link: "https://www.walkandeatspain.com/madrid-neighborhood-market-food-tour",
    },
  ],
};
