/* Madrid guide data.
 * Coordinates: listed where given; otherwise Wikipedia or OSM Nominatim.
 * Do not add places, quotes, or prices that are not in this file.
 */
window.GUIDE = {
  hotel: {
    lat: 40.41857,
    lng: -3.70267,
  },
  /* Default view: Sol/Gran Vía at the south, Chamberí/Malasaña to the north */
  map: {
    center: [40.4282, -3.7024],
    zoom: 14,
  },
  categories: [
    { id: "stay", label: "Stay" },
    { id: "food", label: "Eat" },
    { id: "markets", label: "Markets" },
    { id: "entertainment", label: "See" },
  ],
  places: [
    {
      id: "thompson",
      name: "Thompson Madrid",
      category: "stay",
      neighborhood: "Sol / Gran Vía",
      address: "Plaza del Carmen, s/n, 28013 Madrid",
      lat: 40.41857,
      lng: -3.70267,
      takeaway: "Hyatt / Thompson Hotels. Home base — walking notes are from here.",
      link: "https://www.hyatt.com/hotel/spain/thompson-madrid/madrp",
      linkLabel: "Hyatt listing",
      walk: "You are here",
      coordSource: "provided; matches OSM way/265317799",
    },
    {
      id: "chamberi-market",
      name: "Mercado de Chamberí",
      category: "markets",
      neighborhood: "Chamberí",
      address: "Calle de Alonso Cano, 10, 28010 Madrid",
      lat: 40.43622,
      lng: -3.69762,
      takeaway: "Working market since 1943: produce, meat, fish, plus a gastro area. Weekday mornings best.",
      link: "https://mercadodechamberi.es",
      linkLabel: "mercadodechamberi.es",
      walk: "~2.8 km / ~35 min walk, or Metro",
      shops: [
        {
          name: "Jamonera Castellana",
          note: "Since 1964.",
          link: "https://mercadodechamberi.es/jamonera-castellana",
        },
        {
          name: "Jamonería de Juan",
          note: "Since 1981.",
          link: "https://mercadodechamberi.es/jamoneria-de-juan",
        },
        {
          name: "Casa Tere",
          note: "Mon–Sat mornings typical.",
          link: "https://mercadodechamberi.es/casa-tere",
        },
      ],
      coordSource: "Wikipedia 40.43622222, -3.69761944",
    },
    {
      id: "barcelo",
      name: "Mercado Barceló",
      category: "markets",
      neighborhood: "Chueca / Justicia (Malasaña edge)",
      address: "Calle de Barceló, 6, 28004 Madrid",
      lat: 40.42681,
      lng: -3.69928,
      takeaway: "Modern rebuild: traditional floors plus upper-level food. Walk and Eat Spain tours use this market.",
      link: "https://mercadobarcelo.es/",
      linkLabel: "mercadobarcelo.es",
      extraLinks: [
        { href: "https://mercadobarcelo.es/puestos-mercado", label: "Stall directory" },
      ],
      walk: "~1.5 km / ~18 min walk",
      shops: [
        {
          name: "Ask for Daniel",
          note: "3rd-generation produce. Stall trade name unpublished.",
        },
        {
          name: "Ask for Gemma",
          note: "Cheese. Stall trade name unpublished.",
        },
        {
          name: "Ask for Roberto",
          note: "Olives. Likely Aceitunas del Campo, puesto 215 — not a published stall name on the tour page.",
        },
      ],
      unnamed:
        "Ham slicer José and Pedro & Carlos’s family tapas bar are unpublished — no invented shop names here.",
      confidence: "confirmed",
      confidenceNote: "Confirmed Walk and Eat market. Vendor first names published; stall trade names unpublished.",
      coordSource: "provided",
    },
    {
      id: "aceitunas-del-campo",
      name: "Aceitunas del Campo",
      category: "markets",
      neighborhood: "Mercado Barceló",
      address: "Mercado Barceló, puesto 215, Calle de Barceló, 6, 28004 Madrid",
      lat: 40.42681,
      lng: -3.69928,
      takeaway: "Olive stall inside Barceló. Likely Roberto’s stop on the Walk and Eat market morning.",
      link: "https://mercadobarcelo.es/puestos-mercado",
      linkLabel: "Barceló stall directory",
      walk: "~1.5 km / ~18 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "same building as Mercado Barceló (provided); stall is inside",
    },
    {
      id: "la-comunal",
      name: "La Comunal",
      category: "food",
      neighborhood: "Chueca / Justicia",
      address: "Calle de Mejía Lequerica, 1, 28004 Madrid",
      lat: 40.42596,
      lng: -3.69735,
      takeaway:
        "Fundación Patrimonio Comunal Olivarero olive-oil shop. Walk and Eat partner (Óleo Revista, Nov 2024). Mon–Fri 10:00–14:00 & 17:00–20:00, Sat 10:00–14:00; often closed August.",
      link: "https://www.esmadrid.com/en/shopping/comunal",
      linkLabel: "Turismo Madrid",
      walk: "~2.1 km / ~25 min walk",
      confidence: "confirmed",
      confidenceNote: "Confirmed Walk and Eat partner.",
      coordSource: "OSM node Patrimonio Comunal Olivarero /2777281755",
    },
    {
      id: "vallehermoso",
      name: "Mercado de Vallehermoso",
      category: "markets",
      neighborhood: "Chamberí",
      address: "Calle de Vallehermoso, 36, 28015 Madrid",
      lat: 40.43413,
      lng: -3.70834,
      takeaway: "Framed as a local alternative to San Miguel: working market plus popular food stalls (Tripea among them).",
      link: "https://www.esmadrid.com/compras/mercado-vallehermoso",
      linkLabel: "Turismo Madrid",
      walk: "~2.4 km / ~30 min walk",
      coordSource: "Wikipedia 40.434125, -3.708336",
    },
    {
      id: "mostenses",
      name: "Mercado de los Mostenses",
      category: "markets",
      neighborhood: "Behind Gran Vía",
      address: "Plaza de los Mostenses, 1, 28015 Madrid",
      lat: 40.42329,
      lng: -3.70906,
      takeaway: "Multicultural working market. CN Traveler called it “anti-posh”; José Andrés has praised the Latin American stalls. Renovated 2024 (Turismo Madrid).",
      link: "https://www.esmadrid.com/compras/mercado-de-los-mostenses",
      linkLabel: "Turismo Madrid",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM relation/4425587",
    },
    {
      id: "el-doble",
      name: "El Doble",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle de Ponzano, 58, 28003 Madrid",
      lat: 40.44136,
      lng: -3.69924,
      takeaway: "Standing classic: dobles plus seafood/conservas. Go early. Natural start for a Ponzano evening.",
      link: "https://www.esmadrid.com/restaurantes/el-doble",
      linkLabel: "Turismo Madrid",
      walk: "~2.5 km north / Metro L1 is easier than walking",
      coordSource: "OSM Nominatim for Calle de Ponzano 58",
    },
    {
      id: "ardosa",
      name: "Bodega de La Ardosa",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle de Colón, 13, 28004 Madrid",
      lat: 40.42377,
      lng: -3.70177,
      takeaway: "Vermú and tortilla. CN Traveler: in all the guides, so tourist influx. Arrive before ~7pm.",
      link: "https://www.esmadrid.com/en/restaurants/bodega-ardosa",
      linkLabel: "Turismo Madrid",
      walk: "~0.8 km / ~10 min walk",
      tourist: "heavy",
      coordSource: "OSM node Bodega de la Ardosa /2585147466",
    },
    {
      id: "casa-baranda",
      name: "Casa Baranda",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle de Colón, 11, 28004 Madrid",
      lat: 40.42376,
      lng: -3.70165,
      takeaway: "Ardosa group, next door. Same block, same timing advice.",
      walk: "~0.8 km / ~10 min walk",
      coordSource: "OSM node Casa Baranda /2661123393",
    },
    {
      id: "casa-julio",
      name: "Casa Julio",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle de la Madera, 37, 28004 Madrid",
      lat: 40.42431,
      lng: -3.70366,
      takeaway: "Croquetas since 1921.",
      link: "https://www.esmadrid.com/restaurantes/casa-julio",
      linkLabel: "Turismo Madrid",
      walk: "~1 km / ~12 min walk",
      coordSource: "OSM node Casa Julio /2583954354",
    },
    {
      id: "pez-tortilla",
      name: "Pez Tortilla",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle del Pez, 36, 28004 Madrid",
      lat: 40.42425,
      lng: -3.70649,
      takeaway: "Tortillas, croquetas, craft beer. No reservations. This pin is the Malasaña original, not other branches.",
      link: "https://peztortilla.com/",
      linkLabel: "peztortilla.com",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM node Pez Tortilla /2630111357",
    },
    {
      id: "churreria-madrid-1883",
      name: "Churrería Madrid 1883",
      category: "food",
      neighborhood: "Malasaña",
      address: "Calle del Espíritu Santo, 8, 28004 Madrid",
      lat: 40.42514,
      lng: -3.70258,
      takeaway:
        "Malasaña classic for churros and chocolate. Neighborhood vibe match; not proven as Walk and Eat’s first stop.",
      walk: "~1.3 km / ~16 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM node Madrid 1883 Churreria /6325195806",
    },
    {
      id: "angel-sierra",
      name: "Taberna Ángel Sierra",
      category: "food",
      neighborhood: "Plaza Chueca",
      address: "Calle de Gravina, 11, 28004 Madrid",
      lat: 40.42302,
      lng: -3.69746,
      takeaway: "Historic vermouth taberna. Early is easier than peak evening.",
      link: "https://tabernadeangelsierra.es/",
      linkLabel: "tabernadeangelsierra.es",
      walk: "~1.9 km / ~25 min walk",
      coordSource: "OSM node Taberna de Ángel Sierra /3897299367",
    },
    {
      id: "casa-hortensia",
      name: "Casa Hortensia",
      category: "food",
      neighborhood: "Chueca / Justicia",
      address: "Calle de la Farmacia, 2, 28004 Madrid",
      lat: 40.42387,
      lng: -3.70043,
      takeaway: "Asturian fabada.",
      link: "https://www.esmadrid.com/restaurantes/casa-hortensia",
      linkLabel: "Turismo Madrid",
      walk: "~1 km / ~12 min walk",
      coordSource: "OSM node Casa Hortensia /2661121483",
    },
    {
      id: "caja-de-cerillas",
      name: "Caja de Cerillas",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle de Donoso Cortés, 8, 28015 Madrid",
      lat: 40.43617,
      lng: -3.70547,
      takeaway: "Newer (2025) neo-castizo. Thinner reputation than the old names — book if you go.",
      walk: "~2.4 km / ~30 min walk",
      coordSource: "OSM node Caja De Cerillas /12880638622",
    },
    {
      id: "sala-de-despiece",
      name: "Sala de Despiece (SDD1)",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle de Alonso Cano, 27–28, 28010 Madrid",
      lat: 40.43757,
      lng: -3.69805,
      takeaway:
        "Theatrical counter. Moved here from Ponzano 11. Likely Culinary Backstreets finale per a visitor writeup.",
      walk: "~3.0 km / ~36 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM building Calle de Alonso Cano 27 way/385080174 (OSM still lists the old Ponzano 11 restaurant node; pin uses the stated new address)",
    },
    {
      id: "taberna-la-mina",
      name: "Taberna La Mina",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle del General Álvarez de Castro, 8, 28010 Madrid",
      lat: 40.43483,
      lng: -3.70174,
      takeaway: "Founded 1949. Possible Flavours “since 1949” stop — not a slam dunk.",
      walk: "~2.6 km / ~31 min walk",
      confidence: "likely",
      confidenceNote: "Likely / not confirmed as the tour stop.",
      coordSource: "OSM node Taberna La Mina /2651989201",
    },
    {
      id: "comercial",
      name: "Café Comercial",
      category: "food",
      neighborhood: "Glorieta de Bilbao",
      address: "Glorieta de Bilbao, 7, 28004 Madrid",
      lat: 40.42871,
      lng: -3.70197,
      takeaway: "Historic café. Culinary Backstreets’ Chamberí tour starts here. Mixed “touristy post-reopen” comments.",
      link: "https://www.wheregoesrose.com/madrid-food-tour-culinary-backstreets/",
      linkLabel: "Visitor writeup (wheregoesrose.com)",
      walk: "~2.0 km / ~25 min walk",
      tourist: "soft",
      coordSource: "OSM node Café Comercial /26065697",
    },
    {
      id: "ponzano",
      name: "Calle Ponzano crawl",
      category: "food",
      neighborhood: "Chamberí",
      address: "Calle de Ponzano, Chamberí",
      lat: 40.43767,
      lng: -3.69941,
      takeaway: "“Ponzaning”: a corridor of ~70 bars. Crowded Thu–Sat. Start at El Doble if you only do one.",
      walk: "North of Bilbao; Metro L1 toward Ríos Rosas",
      tourist: "soft-weekends",
      coordSource: "OSM way Calle de Ponzano (Almagro stretch) /8029884",
    },
    {
      id: "anden-0",
      name: "Andén 0 – Estación de Chamberí",
      category: "entertainment",
      neighborhood: "Chamberí",
      address: "Plaza de Chamberí, s/n, 28010 Madrid",
      lat: 40.4323,
      lng: -3.69772,
      takeaway: "Ghost metro museum. Free; book ahead.",
      link: "https://museosmetromadrid.es/estacion-de-chamberi_0/",
      linkLabel: "Museos Metro Madrid",
      walk: "~2.5 km / ~30 min walk",
      coordSource: "Wikipedia 40.4323, -3.69772",
    },
    {
      id: "beti-jai",
      name: "Frontón Beti Jai",
      category: "entertainment",
      neighborhood: "Chamberí / Almagro",
      address: "Calle del Marqués del Riscal, 7, 28010 Madrid",
      lat: 40.43067,
      lng: -3.69116,
      takeaway: "1894 pelota court. National Monument.",
      walk: "~2.3 km / ~28 min walk",
      coordSource: "provided; OSM way/965335844 nearby",
    },
    {
      id: "sorolla",
      name: "Museo Sorolla",
      category: "entertainment",
      neighborhood: "Chamberí / Almagro",
      address: "Paseo del General Martínez Campos, 37, 28010 Madrid",
      lat: 40.4354,
      lng: -3.69254,
      takeaway: "Temporarily closed since October 2024 for expansion. Do not plan a visit.",
      link: "https://www.madrid.es/portales/munimadrid/es/Inicio/Cultura-ocio-y-deporte/Cultura-y-ocio/Direcciones-y-telefonos/Museo-Sorolla/",
      linkLabel: "Ayuntamiento de Madrid",
      closed: true,
      coordSource: "Wikipedia 40.435404, -3.692539",
    },
    {
      id: "geominero",
      name: "Museo Geominero",
      category: "entertainment",
      neighborhood: "Chamberí",
      address: "Calle de Ríos Rosas, 23, 28003 Madrid",
      lat: 40.4427,
      lng: -3.6996,
      takeaway: "Free geology museum. Open mornings.",
      link: "https://www.igme.es/museo/visitanos/",
      linkLabel: "IGME – Visítanos",
      walk: "Near El Doble / Ríos Rosas Metro",
      coordSource: "Wikipedia 40.4427, -3.6996",
    },
    {
      id: "olavide",
      name: "Plaza de Olavide",
      category: "entertainment",
      neighborhood: "Chamberí",
      address: "Plaza de Olavide, 28010 Madrid",
      lat: 40.43305,
      lng: -3.7006,
      takeaway: "Local octagonal plaza with terraces. A pause, not a monument.",
      walk: "~2.2 km / ~27 min walk",
      coordSource: "OSM way Plaza de Olavide /248905968",
    },
    {
      id: "canal",
      name: "Teatros del Canal",
      category: "entertainment",
      neighborhood: "Chamberí",
      address: "Calle de Cea Bermúdez, 1, 28003 Madrid",
      lat: 40.43844,
      lng: -3.70506,
      takeaway: "Performing arts. Check the calendar if you want a show.",
      link: "https://www.teatroscanal.com/",
      linkLabel: "teatroscanal.com",
      walk: "~2.7 km / ~35 min walk",
      coordSource: "Wikipedia 40.438441, -3.705059",
    },
    {
      id: "conde-duque",
      name: "Centro Cultural Conde Duque",
      category: "entertainment",
      neighborhood: "Malasaña / Conde Duque",
      address: "Calle del Conde Duque, 9–11, 28015 Madrid",
      lat: 40.42785,
      lng: -3.71068,
      takeaway: "Municipal cultural centre in the old barracks. Exhibitions, concerts, courtyard.",
      walk: "~1.8 km / ~22 min walk",
      coordSource: "Wikipedia 40.427852, -3.710681",
    },
    {
      id: "historia",
      name: "Museo de Historia de Madrid",
      category: "entertainment",
      neighborhood: "Malasaña",
      address: "Calle de Fuencarral, 78, 28004 Madrid",
      lat: 40.42579,
      lng: -3.70076,
      takeaway: "City history museum on Fuencarral. Useful rainy-hour stop.",
      walk: "~1.1 km / ~14 min walk",
      coordSource: "OSM node Museo de Historia de Madrid /12921081474",
    },
    {
      id: "escultura",
      name: "Museo de Escultura al Aire Libre",
      category: "entertainment",
      neighborhood: "Castellana / Rubén Darío",
      address: "Paseo de la Castellana, 40, 28046 Madrid",
      lat: 40.43303,
      lng: -3.68748,
      takeaway: "Free outdoor sculpture under the Juan Bravo overpass, near Rubén Darío.",
      link: "https://www.esmadrid.com/informacion-turistica/museo-escultura-aire-libre-castellana",
      linkLabel: "Turismo Madrid",
      walk: "~2.5 km / ~30 min walk",
      coordSource: "Wikipedia 40.43303, -3.68748",
    },
    {
      id: "gran-via",
      name: "Gran Vía / Teatro district walk",
      category: "entertainment",
      neighborhood: "Sol / Gran Vía",
      address: "Plaza de Callao / Gran Vía",
      lat: 40.41986,
      lng: -3.70581,
      takeaway: "Theatre stretch of Gran Vía. Short walk from Thompson — evening lights, not a hidden corner.",
      walk: "~0.5 km / a few minutes",
      coordSource: "OSM Plaza de Callao relation/13452454",
    },
  ],
  days: [
    {
      id: "day1",
      title: "Day 1",
      subtitle: "Hotel / Sol",
      transit: "Walk from Thompson. Metro Sol or Gran Vía if you want a ride.",
      slots: [
        {
          id: "stay",
          when: "Stay",
          placeId: "thompson",
          text: "Thompson Madrid, Plaza del Carmen. Home base.",
        },
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "mostenses",
          text: "Mercado de los Mostenses. Working market behind Gran Vía.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "gran-via",
          text: "Gran Vía / teatro walk. Short hop from the hotel.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "ardosa",
          altId: "angel-sierra",
          text: "La Ardosa or Ángel Sierra. Ardosa before ~7pm.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "pez-tortilla",
          altId: "casa-julio",
          text: "Pez Tortilla or Casa Julio. Both nearby in Malasaña.",
        },
      ],
    },
    {
      id: "day2",
      title: "Day 2",
      subtitle: "Chamberí",
      transit: "Metro toward Bilbao or Iglesia / Ríos Rosas. Walk between nearby stops.",
      slots: [
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "chamberi-market",
          text: "Mercado de Chamberí in the morning. Jamón stalls on the card.",
        },
        {
          id: "coffee",
          when: "Coffee",
          placeId: "comercial",
          text: "Café Comercial at Bilbao. Historic, a bit touristy.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "taberna-la-mina",
          altId: "chamberi-market",
          text: "Taberna La Mina (likely) or stay at the market.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "anden-0",
          altId: "olavide",
          text: "Andén 0 (book ahead) or a pause at Plaza de Olavide.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "el-doble",
          altId: "ponzano",
          text: "El Doble, then Ponzano if you want a crawl.",
        },
      ],
    },
    {
      id: "day3",
      title: "Day 3",
      subtitle: "Malasaña / Barceló",
      transit: "Walk north from the hotel, or Metro Tribunal / Alonso Martínez.",
      slots: [
        {
          id: "breakfast",
          when: "Breakfast",
          placeId: "churreria-madrid-1883",
          text: "Churrería Madrid 1883. Likely — neighborhood match, not a confirmed tour stop.",
        },
        {
          id: "coffee",
          when: "Coffee",
          placeId: "la-comunal",
          text: "La Comunal. Olive-oil shop, not a café. Confirmed Walk and Eat partner.",
        },
        {
          id: "lunch",
          when: "Lunch",
          placeId: "barcelo",
          text: "Mercado Barceló. Ask for Daniel, Gemma, Roberto.",
        },
        {
          id: "dinner",
          when: "Dinner",
          placeId: "casa-baranda",
          altId: "ardosa",
          text: "Casa Baranda or La Ardosa. Same Colón block.",
        },
        {
          id: "see",
          when: "Shop or see",
          placeId: "conde-duque",
          altId: "historia",
          text: "Conde Duque or the Museo de Historia on Fuencarral.",
        },
      ],
    },
  ],
  tours: [
    {
      name: "Culinary Backstreets — The Real Madrid",
      detail: "~$160 / 5h in Chamberí. Visitor writeup names Café Comercial; other stops unpublished.",
      link: "https://culinarybackstreets.com/food-tours/madrid/the-real-madrid-markets-tapas-tradition",
    },
    {
      name: "Flavours of Madrid — Chamberí",
      detail: "€99–119. Includes Chamberí Market concepts. Do not assume unpublished stop names.",
      link: "https://www.flavoursofmadrid.com/authentic-madrid-tapas-tour-madrid",
    },
    {
      name: "Walk and Eat Spain — Malasaña market morning",
      detail: "~$100–140. Mercado Barceló. Explicitly skips San Miguel.",
      link: "https://www.walkandeatspain.com/madrid-neighborhood-market-food-tour",
    },
  ],
};
